//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CDLIB
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// D0.
    /// </summary>
    // *** Start programmer edit section *** (D0 CustomAttributes)

    // *** End programmer edit section *** (D0 CustomAttributes)
    [AutoAltered()]
    [ICSSoft.STORMNET.NotStored(false)]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("D0_E", new string[] {
            "Name"})]
    [AssociatedDetailViewAttribute("D0_E", "D1", "D1_E", true, "", "", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("D0_E", "D2", "D2_E", true, "", "", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("D0_E", "D3", "D3_E", true, "", "", true, new string[] {
            ""})]
    [View("FULLD0_E", new string[] {
            "*"}, Hidden=new string[] {
            "*"})]
    [AssociatedDetailViewAttribute("FULLD0_E", "D1", "FULLD1_E", true, "", "", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("FULLD0_E", "D2", "FULLD2_E", true, "", "", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("FULLD0_E", "D3", "FULLD3_E", true, "", "", true, new string[] {
            ""})]
    public class D0 : IIS.CDLIB.D
    {
        
        private IIS.CDLIB.DetailArrayOfD3 fD3;
        
        private IIS.CDLIB.DetailArrayOfD1 fD1;
        
        private IIS.CDLIB.DetailArrayOfD2 fD2;
        
        // *** Start programmer edit section *** (D0 CustomMembers)

        // *** End programmer edit section *** (D0 CustomMembers)

        
        /// <summary>
        /// D0.
        /// </summary>
        // *** Start programmer edit section *** (D0.D3 CustomAttributes)

        // *** End programmer edit section *** (D0.D3 CustomAttributes)
        public virtual IIS.CDLIB.DetailArrayOfD3 D3
        {
            get
            {
                // *** Start programmer edit section *** (D0.D3 Get start)

                // *** End programmer edit section *** (D0.D3 Get start)
                if ((this.fD3 == null))
                {
                    this.fD3 = new IIS.CDLIB.DetailArrayOfD3(this);
                }
                IIS.CDLIB.DetailArrayOfD3 result = this.fD3;
                // *** Start programmer edit section *** (D0.D3 Get end)

                // *** End programmer edit section *** (D0.D3 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (D0.D3 Set start)

                // *** End programmer edit section *** (D0.D3 Set start)
                this.fD3 = value;
                // *** Start programmer edit section *** (D0.D3 Set end)

                // *** End programmer edit section *** (D0.D3 Set end)
            }
        }
        
        /// <summary>
        /// D0.
        /// </summary>
        // *** Start programmer edit section *** (D0.D1 CustomAttributes)

        // *** End programmer edit section *** (D0.D1 CustomAttributes)
        public virtual IIS.CDLIB.DetailArrayOfD1 D1
        {
            get
            {
                // *** Start programmer edit section *** (D0.D1 Get start)

                // *** End programmer edit section *** (D0.D1 Get start)
                if ((this.fD1 == null))
                {
                    this.fD1 = new IIS.CDLIB.DetailArrayOfD1(this);
                }
                IIS.CDLIB.DetailArrayOfD1 result = this.fD1;
                // *** Start programmer edit section *** (D0.D1 Get end)

                // *** End programmer edit section *** (D0.D1 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (D0.D1 Set start)

                // *** End programmer edit section *** (D0.D1 Set start)
                this.fD1 = value;
                // *** Start programmer edit section *** (D0.D1 Set end)

                // *** End programmer edit section *** (D0.D1 Set end)
            }
        }
        
        /// <summary>
        /// D0.
        /// </summary>
        // *** Start programmer edit section *** (D0.D2 CustomAttributes)

        // *** End programmer edit section *** (D0.D2 CustomAttributes)
        public virtual IIS.CDLIB.DetailArrayOfD2 D2
        {
            get
            {
                // *** Start programmer edit section *** (D0.D2 Get start)

                // *** End programmer edit section *** (D0.D2 Get start)
                if ((this.fD2 == null))
                {
                    this.fD2 = new IIS.CDLIB.DetailArrayOfD2(this);
                }
                IIS.CDLIB.DetailArrayOfD2 result = this.fD2;
                // *** Start programmer edit section *** (D0.D2 Get end)

                // *** End programmer edit section *** (D0.D2 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (D0.D2 Set start)

                // *** End programmer edit section *** (D0.D2 Set start)
                this.fD2 = value;
                // *** Start programmer edit section *** (D0.D2 Set end)

                // *** End programmer edit section *** (D0.D2 Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "D0_E" view.
            /// </summary>
            public static ICSSoft.STORMNET.View D0_E
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("D0_E", typeof(IIS.CDLIB.D0));
                }
            }
            
            /// <summary>
            /// "FULLD0_E" view.
            /// </summary>
            public static ICSSoft.STORMNET.View FULLD0_E
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("FULLD0_E", typeof(IIS.CDLIB.D0));
                }
            }
        }
    }
}
