//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CDLIB
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// D1.
    /// </summary>
    // *** Start programmer edit section *** (D1 CustomAttributes)

    // *** End programmer edit section *** (D1 CustomAttributes)
    [AutoAltered()]
    [ICSSoft.STORMNET.NotStored(false)]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("D1_E", new string[] {
            "Name"})]
    [AssociatedDetailViewAttribute("D1_E", "D11", "D11_E", true, "", "", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("D1_E", "D12", "D12_E", true, "", "", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("D1_E", "D13", "D13_E", true, "", "", true, new string[] {
            ""})]
    [View("FULLD1_E", new string[] {
            "*"}, Hidden=new string[] {
            "*"})]
    [AssociatedDetailViewAttribute("FULLD1_E", "D11", "FULLD11_E", true, "", "", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("FULLD1_E", "D12", "FULLD12_E", true, "", "", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("FULLD1_E", "D13", "FULLD13_E", true, "", "", true, new string[] {
            ""})]
    public class D1 : IIS.CDLIB.D
    {
        
        private IIS.CDLIB.DetailArrayOfD13 fD13;
        
        private IIS.CDLIB.DetailArrayOfD11 fD11;
        
        private IIS.CDLIB.DetailArrayOfD12 fD12;
        
        private IIS.CDLIB.D0 fD0;
        
        // *** Start programmer edit section *** (D1 CustomMembers)

        // *** End programmer edit section *** (D1 CustomMembers)

        
        /// <summary>
        /// D1.
        /// </summary>
        // *** Start programmer edit section *** (D1.D13 CustomAttributes)

        // *** End programmer edit section *** (D1.D13 CustomAttributes)
        public virtual IIS.CDLIB.DetailArrayOfD13 D13
        {
            get
            {
                // *** Start programmer edit section *** (D1.D13 Get start)

                // *** End programmer edit section *** (D1.D13 Get start)
                if ((this.fD13 == null))
                {
                    this.fD13 = new IIS.CDLIB.DetailArrayOfD13(this);
                }
                IIS.CDLIB.DetailArrayOfD13 result = this.fD13;
                // *** Start programmer edit section *** (D1.D13 Get end)

                // *** End programmer edit section *** (D1.D13 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (D1.D13 Set start)

                // *** End programmer edit section *** (D1.D13 Set start)
                this.fD13 = value;
                // *** Start programmer edit section *** (D1.D13 Set end)

                // *** End programmer edit section *** (D1.D13 Set end)
            }
        }
        
        /// <summary>
        /// D1.
        /// </summary>
        // *** Start programmer edit section *** (D1.D11 CustomAttributes)

        // *** End programmer edit section *** (D1.D11 CustomAttributes)
        public virtual IIS.CDLIB.DetailArrayOfD11 D11
        {
            get
            {
                // *** Start programmer edit section *** (D1.D11 Get start)

                // *** End programmer edit section *** (D1.D11 Get start)
                if ((this.fD11 == null))
                {
                    this.fD11 = new IIS.CDLIB.DetailArrayOfD11(this);
                }
                IIS.CDLIB.DetailArrayOfD11 result = this.fD11;
                // *** Start programmer edit section *** (D1.D11 Get end)

                // *** End programmer edit section *** (D1.D11 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (D1.D11 Set start)

                // *** End programmer edit section *** (D1.D11 Set start)
                this.fD11 = value;
                // *** Start programmer edit section *** (D1.D11 Set end)

                // *** End programmer edit section *** (D1.D11 Set end)
            }
        }
        
        /// <summary>
        /// D1.
        /// </summary>
        // *** Start programmer edit section *** (D1.D12 CustomAttributes)

        // *** End programmer edit section *** (D1.D12 CustomAttributes)
        public virtual IIS.CDLIB.DetailArrayOfD12 D12
        {
            get
            {
                // *** Start programmer edit section *** (D1.D12 Get start)

                // *** End programmer edit section *** (D1.D12 Get start)
                if ((this.fD12 == null))
                {
                    this.fD12 = new IIS.CDLIB.DetailArrayOfD12(this);
                }
                IIS.CDLIB.DetailArrayOfD12 result = this.fD12;
                // *** Start programmer edit section *** (D1.D12 Get end)

                // *** End programmer edit section *** (D1.D12 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (D1.D12 Set start)

                // *** End programmer edit section *** (D1.D12 Set start)
                this.fD12 = value;
                // *** Start programmer edit section *** (D1.D12 Set end)

                // *** End programmer edit section *** (D1.D12 Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.CDLIB.D0.
        /// </summary>
        // *** Start programmer edit section *** (D1.D0 CustomAttributes)

        // *** End programmer edit section *** (D1.D0 CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "D0"})]
        public virtual IIS.CDLIB.D0 D0
        {
            get
            {
                // *** Start programmer edit section *** (D1.D0 Get start)

                // *** End programmer edit section *** (D1.D0 Get start)
                IIS.CDLIB.D0 result = this.fD0;
                // *** Start programmer edit section *** (D1.D0 Get end)

                // *** End programmer edit section *** (D1.D0 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (D1.D0 Set start)

                // *** End programmer edit section *** (D1.D0 Set start)
                this.fD0 = value;
                // *** Start programmer edit section *** (D1.D0 Set end)

                // *** End programmer edit section *** (D1.D0 Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "D1_E" view.
            /// </summary>
            public static ICSSoft.STORMNET.View D1_E
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("D1_E", typeof(IIS.CDLIB.D1));
                }
            }
            
            /// <summary>
            /// "FULLD1_E" view.
            /// </summary>
            public static ICSSoft.STORMNET.View FULLD1_E
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("FULLD1_E", typeof(IIS.CDLIB.D1));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of D1.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfD1 CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfD1 CustomAttributes)
    public class DetailArrayOfD1 : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.CDLIB.DetailArrayOfD1 members)

        // *** End programmer edit section *** (IIS.CDLIB.DetailArrayOfD1 members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type D1 by index.
        /// </summary>
        /// <summary>
        /// Adds object with type D1.
        /// </summary>
        public DetailArrayOfD1(IIS.CDLIB.D0 fD0) : 
                base(typeof(D1), ((ICSSoft.STORMNET.DataObject)(fD0)))
        {
        }
        
        public IIS.CDLIB.D1 this[int index]
        {
            get
            {
                return ((IIS.CDLIB.D1)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.CDLIB.D1 dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
