//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CDLIB
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// D11.
    /// </summary>
    // *** Start programmer edit section *** (D11 CustomAttributes)

    // *** End programmer edit section *** (D11 CustomAttributes)
    [AutoAltered()]
    [ICSSoft.STORMNET.NotStored(false)]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("D11_E", new string[] {
            "Name"})]
    [AssociatedDetailViewAttribute("D11_E", "D111", "D_E", true, "", "", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("D11_E", "D112", "D_E", true, "", "", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("D11_E", "D113", "D_E", true, "", "", true, new string[] {
            ""})]
    [View("FULLD11_E", new string[] {
            "*"}, Hidden=new string[] {
            "*"})]
    [AssociatedDetailViewAttribute("FULLD11_E", "D111", "FULLD_E", true, "", "", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("FULLD11_E", "D112", "FULLD_E", true, "", "", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("FULLD11_E", "D113", "FULLD_E", true, "", "", true, new string[] {
            ""})]
    public class D11 : IIS.CDLIB.D
    {
        
        private IIS.CDLIB.DetailArrayOfD112 fD112;
        
        private IIS.CDLIB.DetailArrayOfD111 fD111;
        
        private IIS.CDLIB.DetailArrayOfD113 fD113;
        
        private IIS.CDLIB.D1 fD1;
        
        // *** Start programmer edit section *** (D11 CustomMembers)

        // *** End programmer edit section *** (D11 CustomMembers)

        
        /// <summary>
        /// D11.
        /// </summary>
        // *** Start programmer edit section *** (D11.D112 CustomAttributes)

        // *** End programmer edit section *** (D11.D112 CustomAttributes)
        public virtual IIS.CDLIB.DetailArrayOfD112 D112
        {
            get
            {
                // *** Start programmer edit section *** (D11.D112 Get start)

                // *** End programmer edit section *** (D11.D112 Get start)
                if ((this.fD112 == null))
                {
                    this.fD112 = new IIS.CDLIB.DetailArrayOfD112(this);
                }
                IIS.CDLIB.DetailArrayOfD112 result = this.fD112;
                // *** Start programmer edit section *** (D11.D112 Get end)

                // *** End programmer edit section *** (D11.D112 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (D11.D112 Set start)

                // *** End programmer edit section *** (D11.D112 Set start)
                this.fD112 = value;
                // *** Start programmer edit section *** (D11.D112 Set end)

                // *** End programmer edit section *** (D11.D112 Set end)
            }
        }
        
        /// <summary>
        /// D11.
        /// </summary>
        // *** Start programmer edit section *** (D11.D111 CustomAttributes)

        // *** End programmer edit section *** (D11.D111 CustomAttributes)
        public virtual IIS.CDLIB.DetailArrayOfD111 D111
        {
            get
            {
                // *** Start programmer edit section *** (D11.D111 Get start)

                // *** End programmer edit section *** (D11.D111 Get start)
                if ((this.fD111 == null))
                {
                    this.fD111 = new IIS.CDLIB.DetailArrayOfD111(this);
                }
                IIS.CDLIB.DetailArrayOfD111 result = this.fD111;
                // *** Start programmer edit section *** (D11.D111 Get end)

                // *** End programmer edit section *** (D11.D111 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (D11.D111 Set start)

                // *** End programmer edit section *** (D11.D111 Set start)
                this.fD111 = value;
                // *** Start programmer edit section *** (D11.D111 Set end)

                // *** End programmer edit section *** (D11.D111 Set end)
            }
        }
        
        /// <summary>
        /// D11.
        /// </summary>
        // *** Start programmer edit section *** (D11.D113 CustomAttributes)

        // *** End programmer edit section *** (D11.D113 CustomAttributes)
        public virtual IIS.CDLIB.DetailArrayOfD113 D113
        {
            get
            {
                // *** Start programmer edit section *** (D11.D113 Get start)

                // *** End programmer edit section *** (D11.D113 Get start)
                if ((this.fD113 == null))
                {
                    this.fD113 = new IIS.CDLIB.DetailArrayOfD113(this);
                }
                IIS.CDLIB.DetailArrayOfD113 result = this.fD113;
                // *** Start programmer edit section *** (D11.D113 Get end)

                // *** End programmer edit section *** (D11.D113 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (D11.D113 Set start)

                // *** End programmer edit section *** (D11.D113 Set start)
                this.fD113 = value;
                // *** Start programmer edit section *** (D11.D113 Set end)

                // *** End programmer edit section *** (D11.D113 Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.CDLIB.D1.
        /// </summary>
        // *** Start programmer edit section *** (D11.D1 CustomAttributes)

        // *** End programmer edit section *** (D11.D1 CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "D1"})]
        public virtual IIS.CDLIB.D1 D1
        {
            get
            {
                // *** Start programmer edit section *** (D11.D1 Get start)

                // *** End programmer edit section *** (D11.D1 Get start)
                IIS.CDLIB.D1 result = this.fD1;
                // *** Start programmer edit section *** (D11.D1 Get end)

                // *** End programmer edit section *** (D11.D1 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (D11.D1 Set start)

                // *** End programmer edit section *** (D11.D1 Set start)
                this.fD1 = value;
                // *** Start programmer edit section *** (D11.D1 Set end)

                // *** End programmer edit section *** (D11.D1 Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "D11_E" view.
            /// </summary>
            public static ICSSoft.STORMNET.View D11_E
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("D11_E", typeof(IIS.CDLIB.D11));
                }
            }
            
            /// <summary>
            /// "FULLD11_E" view.
            /// </summary>
            public static ICSSoft.STORMNET.View FULLD11_E
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("FULLD11_E", typeof(IIS.CDLIB.D11));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of D11.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfD11 CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfD11 CustomAttributes)
    public class DetailArrayOfD11 : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.CDLIB.DetailArrayOfD11 members)

        // *** End programmer edit section *** (IIS.CDLIB.DetailArrayOfD11 members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type D11 by index.
        /// </summary>
        /// <summary>
        /// Adds object with type D11.
        /// </summary>
        public DetailArrayOfD11(IIS.CDLIB.D1 fD1) : 
                base(typeof(D11), ((ICSSoft.STORMNET.DataObject)(fD1)))
        {
        }
        
        public IIS.CDLIB.D11 this[int index]
        {
            get
            {
                return ((IIS.CDLIB.D11)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.CDLIB.D11 dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
