//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CDLIB
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// D113.
    /// </summary>
    // *** Start programmer edit section *** (D113 CustomAttributes)

    // *** End programmer edit section *** (D113 CustomAttributes)
    [AutoAltered()]
    [ICSSoft.STORMNET.NotStored(false)]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class D113 : IIS.CDLIB.D
    {
        
        private IIS.CDLIB.D11 fD11;
        
        // *** Start programmer edit section *** (D113 CustomMembers)

        // *** End programmer edit section *** (D113 CustomMembers)

        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.CDLIB.D11.
        /// </summary>
        // *** Start programmer edit section *** (D113.D11 CustomAttributes)

        // *** End programmer edit section *** (D113.D11 CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "D11"})]
        public virtual IIS.CDLIB.D11 D11
        {
            get
            {
                // *** Start programmer edit section *** (D113.D11 Get start)

                // *** End programmer edit section *** (D113.D11 Get start)
                IIS.CDLIB.D11 result = this.fD11;
                // *** Start programmer edit section *** (D113.D11 Get end)

                // *** End programmer edit section *** (D113.D11 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (D113.D11 Set start)

                // *** End programmer edit section *** (D113.D11 Set start)
                this.fD11 = value;
                // *** Start programmer edit section *** (D113.D11 Set end)

                // *** End programmer edit section *** (D113.D11 Set end)
            }
        }
    }
    
    /// <summary>
    /// Detail array of D113.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfD113 CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfD113 CustomAttributes)
    public class DetailArrayOfD113 : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.CDLIB.DetailArrayOfD113 members)

        // *** End programmer edit section *** (IIS.CDLIB.DetailArrayOfD113 members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type D113 by index.
        /// </summary>
        /// <summary>
        /// Adds object with type D113.
        /// </summary>
        public DetailArrayOfD113(IIS.CDLIB.D11 fD11) : 
                base(typeof(D113), ((ICSSoft.STORMNET.DataObject)(fD11)))
        {
        }
        
        public IIS.CDLIB.D113 this[int index]
        {
            get
            {
                return ((IIS.CDLIB.D113)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.CDLIB.D113 dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
