//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CDLIB
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// D12.
    /// </summary>
    // *** Start programmer edit section *** (D12 CustomAttributes)

    // *** End programmer edit section *** (D12 CustomAttributes)
    [AutoAltered()]
    [ICSSoft.STORMNET.NotStored(false)]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("D12_E", new string[] {
            "Name"})]
    [AssociatedDetailViewAttribute("D12_E", "D121", "D_E", true, "", "", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("D12_E", "D122", "D_E", true, "", "", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("D12_E", "D123", "D_E", true, "", "", true, new string[] {
            ""})]
    [View("FULLD12_E", new string[] {
            "*"}, Hidden=new string[] {
            "*"})]
    [AssociatedDetailViewAttribute("FULLD12_E", "D121", "FULLD_E", true, "", "", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("FULLD12_E", "D122", "FULLD_E", true, "", "", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("FULLD12_E", "D123", "FULLD_E", true, "", "", true, new string[] {
            ""})]
    public class D12 : IIS.CDLIB.D
    {
        
        private IIS.CDLIB.DetailArrayOfD122 fD122;
        
        private IIS.CDLIB.DetailArrayOfD121 fD121;
        
        private IIS.CDLIB.DetailArrayOfD123 fD123;
        
        private IIS.CDLIB.D1 fD1;
        
        // *** Start programmer edit section *** (D12 CustomMembers)

        // *** End programmer edit section *** (D12 CustomMembers)

        
        /// <summary>
        /// D12.
        /// </summary>
        // *** Start programmer edit section *** (D12.D122 CustomAttributes)

        // *** End programmer edit section *** (D12.D122 CustomAttributes)
        public virtual IIS.CDLIB.DetailArrayOfD122 D122
        {
            get
            {
                // *** Start programmer edit section *** (D12.D122 Get start)

                // *** End programmer edit section *** (D12.D122 Get start)
                if ((this.fD122 == null))
                {
                    this.fD122 = new IIS.CDLIB.DetailArrayOfD122(this);
                }
                IIS.CDLIB.DetailArrayOfD122 result = this.fD122;
                // *** Start programmer edit section *** (D12.D122 Get end)

                // *** End programmer edit section *** (D12.D122 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (D12.D122 Set start)

                // *** End programmer edit section *** (D12.D122 Set start)
                this.fD122 = value;
                // *** Start programmer edit section *** (D12.D122 Set end)

                // *** End programmer edit section *** (D12.D122 Set end)
            }
        }
        
        /// <summary>
        /// D12.
        /// </summary>
        // *** Start programmer edit section *** (D12.D121 CustomAttributes)

        // *** End programmer edit section *** (D12.D121 CustomAttributes)
        public virtual IIS.CDLIB.DetailArrayOfD121 D121
        {
            get
            {
                // *** Start programmer edit section *** (D12.D121 Get start)

                // *** End programmer edit section *** (D12.D121 Get start)
                if ((this.fD121 == null))
                {
                    this.fD121 = new IIS.CDLIB.DetailArrayOfD121(this);
                }
                IIS.CDLIB.DetailArrayOfD121 result = this.fD121;
                // *** Start programmer edit section *** (D12.D121 Get end)

                // *** End programmer edit section *** (D12.D121 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (D12.D121 Set start)

                // *** End programmer edit section *** (D12.D121 Set start)
                this.fD121 = value;
                // *** Start programmer edit section *** (D12.D121 Set end)

                // *** End programmer edit section *** (D12.D121 Set end)
            }
        }
        
        /// <summary>
        /// D12.
        /// </summary>
        // *** Start programmer edit section *** (D12.D123 CustomAttributes)

        // *** End programmer edit section *** (D12.D123 CustomAttributes)
        public virtual IIS.CDLIB.DetailArrayOfD123 D123
        {
            get
            {
                // *** Start programmer edit section *** (D12.D123 Get start)

                // *** End programmer edit section *** (D12.D123 Get start)
                if ((this.fD123 == null))
                {
                    this.fD123 = new IIS.CDLIB.DetailArrayOfD123(this);
                }
                IIS.CDLIB.DetailArrayOfD123 result = this.fD123;
                // *** Start programmer edit section *** (D12.D123 Get end)

                // *** End programmer edit section *** (D12.D123 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (D12.D123 Set start)

                // *** End programmer edit section *** (D12.D123 Set start)
                this.fD123 = value;
                // *** Start programmer edit section *** (D12.D123 Set end)

                // *** End programmer edit section *** (D12.D123 Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.CDLIB.D1.
        /// </summary>
        // *** Start programmer edit section *** (D12.D1 CustomAttributes)

        // *** End programmer edit section *** (D12.D1 CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "D1"})]
        public virtual IIS.CDLIB.D1 D1
        {
            get
            {
                // *** Start programmer edit section *** (D12.D1 Get start)

                // *** End programmer edit section *** (D12.D1 Get start)
                IIS.CDLIB.D1 result = this.fD1;
                // *** Start programmer edit section *** (D12.D1 Get end)

                // *** End programmer edit section *** (D12.D1 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (D12.D1 Set start)

                // *** End programmer edit section *** (D12.D1 Set start)
                this.fD1 = value;
                // *** Start programmer edit section *** (D12.D1 Set end)

                // *** End programmer edit section *** (D12.D1 Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "D12_E" view.
            /// </summary>
            public static ICSSoft.STORMNET.View D12_E
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("D12_E", typeof(IIS.CDLIB.D12));
                }
            }
            
            /// <summary>
            /// "FULLD12_E" view.
            /// </summary>
            public static ICSSoft.STORMNET.View FULLD12_E
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("FULLD12_E", typeof(IIS.CDLIB.D12));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of D12.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfD12 CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfD12 CustomAttributes)
    public class DetailArrayOfD12 : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.CDLIB.DetailArrayOfD12 members)

        // *** End programmer edit section *** (IIS.CDLIB.DetailArrayOfD12 members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type D12 by index.
        /// </summary>
        /// <summary>
        /// Adds object with type D12.
        /// </summary>
        public DetailArrayOfD12(IIS.CDLIB.D1 fD1) : 
                base(typeof(D12), ((ICSSoft.STORMNET.DataObject)(fD1)))
        {
        }
        
        public IIS.CDLIB.D12 this[int index]
        {
            get
            {
                return ((IIS.CDLIB.D12)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.CDLIB.D12 dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
