//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CDLIB
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// D122.
    /// </summary>
    // *** Start programmer edit section *** (D122 CustomAttributes)

    // *** End programmer edit section *** (D122 CustomAttributes)
    [AutoAltered()]
    [ICSSoft.STORMNET.NotStored(false)]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class D122 : IIS.CDLIB.D
    {
        
        private IIS.CDLIB.D12 fD12;
        
        // *** Start programmer edit section *** (D122 CustomMembers)

        // *** End programmer edit section *** (D122 CustomMembers)

        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.CDLIB.D12.
        /// </summary>
        // *** Start programmer edit section *** (D122.D12 CustomAttributes)

        // *** End programmer edit section *** (D122.D12 CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "D12"})]
        public virtual IIS.CDLIB.D12 D12
        {
            get
            {
                // *** Start programmer edit section *** (D122.D12 Get start)

                // *** End programmer edit section *** (D122.D12 Get start)
                IIS.CDLIB.D12 result = this.fD12;
                // *** Start programmer edit section *** (D122.D12 Get end)

                // *** End programmer edit section *** (D122.D12 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (D122.D12 Set start)

                // *** End programmer edit section *** (D122.D12 Set start)
                this.fD12 = value;
                // *** Start programmer edit section *** (D122.D12 Set end)

                // *** End programmer edit section *** (D122.D12 Set end)
            }
        }
    }
    
    /// <summary>
    /// Detail array of D122.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfD122 CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfD122 CustomAttributes)
    public class DetailArrayOfD122 : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.CDLIB.DetailArrayOfD122 members)

        // *** End programmer edit section *** (IIS.CDLIB.DetailArrayOfD122 members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type D122 by index.
        /// </summary>
        /// <summary>
        /// Adds object with type D122.
        /// </summary>
        public DetailArrayOfD122(IIS.CDLIB.D12 fD12) : 
                base(typeof(D122), ((ICSSoft.STORMNET.DataObject)(fD12)))
        {
        }
        
        public IIS.CDLIB.D122 this[int index]
        {
            get
            {
                return ((IIS.CDLIB.D122)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.CDLIB.D122 dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
