//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CDLIB
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// D13.
    /// </summary>
    // *** Start programmer edit section *** (D13 CustomAttributes)

    // *** End programmer edit section *** (D13 CustomAttributes)
    [AutoAltered()]
    [ICSSoft.STORMNET.NotStored(false)]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("D13_E", new string[] {
            "Name"})]
    [AssociatedDetailViewAttribute("D13_E", "D131", "D_E", true, "", "", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("D13_E", "D132", "D_E", true, "", "", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("D13_E", "D133", "D_E", true, "", "", true, new string[] {
            ""})]
    [View("FULLD13_E", new string[] {
            "*"}, Hidden=new string[] {
            "*"})]
    [AssociatedDetailViewAttribute("FULLD13_E", "D131", "FULLD_E", true, "", "", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("FULLD13_E", "D132", "FULLD_E", true, "", "", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("FULLD13_E", "D133", "FULLD_E", true, "", "", true, new string[] {
            ""})]
    public class D13 : IIS.CDLIB.D
    {
        
        private IIS.CDLIB.DetailArrayOfD133 fD133;
        
        private IIS.CDLIB.DetailArrayOfD131 fD131;
        
        private IIS.CDLIB.DetailArrayOfD132 fD132;
        
        private IIS.CDLIB.D1 fD1;
        
        // *** Start programmer edit section *** (D13 CustomMembers)

        // *** End programmer edit section *** (D13 CustomMembers)

        
        /// <summary>
        /// D13.
        /// </summary>
        // *** Start programmer edit section *** (D13.D133 CustomAttributes)

        // *** End programmer edit section *** (D13.D133 CustomAttributes)
        public virtual IIS.CDLIB.DetailArrayOfD133 D133
        {
            get
            {
                // *** Start programmer edit section *** (D13.D133 Get start)

                // *** End programmer edit section *** (D13.D133 Get start)
                if ((this.fD133 == null))
                {
                    this.fD133 = new IIS.CDLIB.DetailArrayOfD133(this);
                }
                IIS.CDLIB.DetailArrayOfD133 result = this.fD133;
                // *** Start programmer edit section *** (D13.D133 Get end)

                // *** End programmer edit section *** (D13.D133 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (D13.D133 Set start)

                // *** End programmer edit section *** (D13.D133 Set start)
                this.fD133 = value;
                // *** Start programmer edit section *** (D13.D133 Set end)

                // *** End programmer edit section *** (D13.D133 Set end)
            }
        }
        
        /// <summary>
        /// D13.
        /// </summary>
        // *** Start programmer edit section *** (D13.D131 CustomAttributes)

        // *** End programmer edit section *** (D13.D131 CustomAttributes)
        public virtual IIS.CDLIB.DetailArrayOfD131 D131
        {
            get
            {
                // *** Start programmer edit section *** (D13.D131 Get start)

                // *** End programmer edit section *** (D13.D131 Get start)
                if ((this.fD131 == null))
                {
                    this.fD131 = new IIS.CDLIB.DetailArrayOfD131(this);
                }
                IIS.CDLIB.DetailArrayOfD131 result = this.fD131;
                // *** Start programmer edit section *** (D13.D131 Get end)

                // *** End programmer edit section *** (D13.D131 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (D13.D131 Set start)

                // *** End programmer edit section *** (D13.D131 Set start)
                this.fD131 = value;
                // *** Start programmer edit section *** (D13.D131 Set end)

                // *** End programmer edit section *** (D13.D131 Set end)
            }
        }
        
        /// <summary>
        /// D13.
        /// </summary>
        // *** Start programmer edit section *** (D13.D132 CustomAttributes)

        // *** End programmer edit section *** (D13.D132 CustomAttributes)
        public virtual IIS.CDLIB.DetailArrayOfD132 D132
        {
            get
            {
                // *** Start programmer edit section *** (D13.D132 Get start)

                // *** End programmer edit section *** (D13.D132 Get start)
                if ((this.fD132 == null))
                {
                    this.fD132 = new IIS.CDLIB.DetailArrayOfD132(this);
                }
                IIS.CDLIB.DetailArrayOfD132 result = this.fD132;
                // *** Start programmer edit section *** (D13.D132 Get end)

                // *** End programmer edit section *** (D13.D132 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (D13.D132 Set start)

                // *** End programmer edit section *** (D13.D132 Set start)
                this.fD132 = value;
                // *** Start programmer edit section *** (D13.D132 Set end)

                // *** End programmer edit section *** (D13.D132 Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.CDLIB.D1.
        /// </summary>
        // *** Start programmer edit section *** (D13.D1 CustomAttributes)

        // *** End programmer edit section *** (D13.D1 CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "D1"})]
        public virtual IIS.CDLIB.D1 D1
        {
            get
            {
                // *** Start programmer edit section *** (D13.D1 Get start)

                // *** End programmer edit section *** (D13.D1 Get start)
                IIS.CDLIB.D1 result = this.fD1;
                // *** Start programmer edit section *** (D13.D1 Get end)

                // *** End programmer edit section *** (D13.D1 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (D13.D1 Set start)

                // *** End programmer edit section *** (D13.D1 Set start)
                this.fD1 = value;
                // *** Start programmer edit section *** (D13.D1 Set end)

                // *** End programmer edit section *** (D13.D1 Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "D13_E" view.
            /// </summary>
            public static ICSSoft.STORMNET.View D13_E
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("D13_E", typeof(IIS.CDLIB.D13));
                }
            }
            
            /// <summary>
            /// "FULLD13_E" view.
            /// </summary>
            public static ICSSoft.STORMNET.View FULLD13_E
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("FULLD13_E", typeof(IIS.CDLIB.D13));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of D13.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfD13 CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfD13 CustomAttributes)
    public class DetailArrayOfD13 : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.CDLIB.DetailArrayOfD13 members)

        // *** End programmer edit section *** (IIS.CDLIB.DetailArrayOfD13 members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type D13 by index.
        /// </summary>
        /// <summary>
        /// Adds object with type D13.
        /// </summary>
        public DetailArrayOfD13(IIS.CDLIB.D1 fD1) : 
                base(typeof(D13), ((ICSSoft.STORMNET.DataObject)(fD1)))
        {
        }
        
        public IIS.CDLIB.D13 this[int index]
        {
            get
            {
                return ((IIS.CDLIB.D13)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.CDLIB.D13 dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
