//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CDLIB
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// D131.
    /// </summary>
    // *** Start programmer edit section *** (D131 CustomAttributes)

    // *** End programmer edit section *** (D131 CustomAttributes)
    [AutoAltered()]
    [ICSSoft.STORMNET.NotStored(false)]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class D131 : IIS.CDLIB.D
    {
        
        private IIS.CDLIB.D13 fD13;
        
        // *** Start programmer edit section *** (D131 CustomMembers)

        // *** End programmer edit section *** (D131 CustomMembers)

        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.CDLIB.D13.
        /// </summary>
        // *** Start programmer edit section *** (D131.D13 CustomAttributes)

        // *** End programmer edit section *** (D131.D13 CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "D13"})]
        public virtual IIS.CDLIB.D13 D13
        {
            get
            {
                // *** Start programmer edit section *** (D131.D13 Get start)

                // *** End programmer edit section *** (D131.D13 Get start)
                IIS.CDLIB.D13 result = this.fD13;
                // *** Start programmer edit section *** (D131.D13 Get end)

                // *** End programmer edit section *** (D131.D13 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (D131.D13 Set start)

                // *** End programmer edit section *** (D131.D13 Set start)
                this.fD13 = value;
                // *** Start programmer edit section *** (D131.D13 Set end)

                // *** End programmer edit section *** (D131.D13 Set end)
            }
        }
    }
    
    /// <summary>
    /// Detail array of D131.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfD131 CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfD131 CustomAttributes)
    public class DetailArrayOfD131 : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.CDLIB.DetailArrayOfD131 members)

        // *** End programmer edit section *** (IIS.CDLIB.DetailArrayOfD131 members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type D131 by index.
        /// </summary>
        /// <summary>
        /// Adds object with type D131.
        /// </summary>
        public DetailArrayOfD131(IIS.CDLIB.D13 fD13) : 
                base(typeof(D131), ((ICSSoft.STORMNET.DataObject)(fD13)))
        {
        }
        
        public IIS.CDLIB.D131 this[int index]
        {
            get
            {
                return ((IIS.CDLIB.D131)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.CDLIB.D131 dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
