//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CDLIB
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// D2.
    /// </summary>
    // *** Start programmer edit section *** (D2 CustomAttributes)

    // *** End programmer edit section *** (D2 CustomAttributes)
    [AutoAltered()]
    [ICSSoft.STORMNET.NotStored(false)]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("D2_E", new string[] {
            "Name"})]
    [AssociatedDetailViewAttribute("D2_E", "D21", "D21_E", true, "", "", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("D2_E", "D22", "D22_E", true, "", "", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("D2_E", "D23", "D23_E", true, "", "", true, new string[] {
            ""})]
    [View("FULLD2_E", new string[] {
            "*"}, Hidden=new string[] {
            "*"})]
    [AssociatedDetailViewAttribute("FULLD2_E", "D21", "FULLD21_E", true, "", "", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("FULLD2_E", "D22", "FULLD22_E", true, "", "", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("FULLD2_E", "D23", "FULLD23_E", true, "", "", true, new string[] {
            ""})]
    public class D2 : IIS.CDLIB.D
    {
        
        private IIS.CDLIB.DetailArrayOfD23 fD23;
        
        private IIS.CDLIB.DetailArrayOfD21 fD21;
        
        private IIS.CDLIB.DetailArrayOfD22 fD22;
        
        private IIS.CDLIB.D0 fD0;
        
        // *** Start programmer edit section *** (D2 CustomMembers)

        // *** End programmer edit section *** (D2 CustomMembers)

        
        /// <summary>
        /// D2.
        /// </summary>
        // *** Start programmer edit section *** (D2.D23 CustomAttributes)

        // *** End programmer edit section *** (D2.D23 CustomAttributes)
        public virtual IIS.CDLIB.DetailArrayOfD23 D23
        {
            get
            {
                // *** Start programmer edit section *** (D2.D23 Get start)

                // *** End programmer edit section *** (D2.D23 Get start)
                if ((this.fD23 == null))
                {
                    this.fD23 = new IIS.CDLIB.DetailArrayOfD23(this);
                }
                IIS.CDLIB.DetailArrayOfD23 result = this.fD23;
                // *** Start programmer edit section *** (D2.D23 Get end)

                // *** End programmer edit section *** (D2.D23 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (D2.D23 Set start)

                // *** End programmer edit section *** (D2.D23 Set start)
                this.fD23 = value;
                // *** Start programmer edit section *** (D2.D23 Set end)

                // *** End programmer edit section *** (D2.D23 Set end)
            }
        }
        
        /// <summary>
        /// D2.
        /// </summary>
        // *** Start programmer edit section *** (D2.D21 CustomAttributes)

        // *** End programmer edit section *** (D2.D21 CustomAttributes)
        public virtual IIS.CDLIB.DetailArrayOfD21 D21
        {
            get
            {
                // *** Start programmer edit section *** (D2.D21 Get start)

                // *** End programmer edit section *** (D2.D21 Get start)
                if ((this.fD21 == null))
                {
                    this.fD21 = new IIS.CDLIB.DetailArrayOfD21(this);
                }
                IIS.CDLIB.DetailArrayOfD21 result = this.fD21;
                // *** Start programmer edit section *** (D2.D21 Get end)

                // *** End programmer edit section *** (D2.D21 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (D2.D21 Set start)

                // *** End programmer edit section *** (D2.D21 Set start)
                this.fD21 = value;
                // *** Start programmer edit section *** (D2.D21 Set end)

                // *** End programmer edit section *** (D2.D21 Set end)
            }
        }
        
        /// <summary>
        /// D2.
        /// </summary>
        // *** Start programmer edit section *** (D2.D22 CustomAttributes)

        // *** End programmer edit section *** (D2.D22 CustomAttributes)
        public virtual IIS.CDLIB.DetailArrayOfD22 D22
        {
            get
            {
                // *** Start programmer edit section *** (D2.D22 Get start)

                // *** End programmer edit section *** (D2.D22 Get start)
                if ((this.fD22 == null))
                {
                    this.fD22 = new IIS.CDLIB.DetailArrayOfD22(this);
                }
                IIS.CDLIB.DetailArrayOfD22 result = this.fD22;
                // *** Start programmer edit section *** (D2.D22 Get end)

                // *** End programmer edit section *** (D2.D22 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (D2.D22 Set start)

                // *** End programmer edit section *** (D2.D22 Set start)
                this.fD22 = value;
                // *** Start programmer edit section *** (D2.D22 Set end)

                // *** End programmer edit section *** (D2.D22 Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.CDLIB.D0.
        /// </summary>
        // *** Start programmer edit section *** (D2.D0 CustomAttributes)

        // *** End programmer edit section *** (D2.D0 CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "D0"})]
        public virtual IIS.CDLIB.D0 D0
        {
            get
            {
                // *** Start programmer edit section *** (D2.D0 Get start)

                // *** End programmer edit section *** (D2.D0 Get start)
                IIS.CDLIB.D0 result = this.fD0;
                // *** Start programmer edit section *** (D2.D0 Get end)

                // *** End programmer edit section *** (D2.D0 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (D2.D0 Set start)

                // *** End programmer edit section *** (D2.D0 Set start)
                this.fD0 = value;
                // *** Start programmer edit section *** (D2.D0 Set end)

                // *** End programmer edit section *** (D2.D0 Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "D2_E" view.
            /// </summary>
            public static ICSSoft.STORMNET.View D2_E
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("D2_E", typeof(IIS.CDLIB.D2));
                }
            }
            
            /// <summary>
            /// "FULLD2_E" view.
            /// </summary>
            public static ICSSoft.STORMNET.View FULLD2_E
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("FULLD2_E", typeof(IIS.CDLIB.D2));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of D2.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfD2 CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfD2 CustomAttributes)
    public class DetailArrayOfD2 : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.CDLIB.DetailArrayOfD2 members)

        // *** End programmer edit section *** (IIS.CDLIB.DetailArrayOfD2 members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type D2 by index.
        /// </summary>
        /// <summary>
        /// Adds object with type D2.
        /// </summary>
        public DetailArrayOfD2(IIS.CDLIB.D0 fD0) : 
                base(typeof(D2), ((ICSSoft.STORMNET.DataObject)(fD0)))
        {
        }
        
        public IIS.CDLIB.D2 this[int index]
        {
            get
            {
                return ((IIS.CDLIB.D2)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.CDLIB.D2 dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
