//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CDLIB
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// D21.
    /// </summary>
    // *** Start programmer edit section *** (D21 CustomAttributes)

    // *** End programmer edit section *** (D21 CustomAttributes)
    [AutoAltered()]
    [ICSSoft.STORMNET.NotStored(false)]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("D21_E", new string[] {
            "Name"})]
    [AssociatedDetailViewAttribute("D21_E", "D211", "D_E", true, "", "", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("D21_E", "D212", "D_E", true, "", "", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("D21_E", "D213", "D_E", true, "", "", true, new string[] {
            ""})]
    [View("FULLD21_E", new string[] {
            "*"}, Hidden=new string[] {
            "*"})]
    [AssociatedDetailViewAttribute("FULLD21_E", "D211", "FULLD_E", true, "", "", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("FULLD21_E", "D212", "FULLD_E", true, "", "", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("FULLD21_E", "D213", "FULLD_E", true, "", "", true, new string[] {
            ""})]
    public class D21 : IIS.CDLIB.D
    {
        
        private IIS.CDLIB.DetailArrayOfD212 fD212;
        
        private IIS.CDLIB.DetailArrayOfD213 fD213;
        
        private IIS.CDLIB.DetailArrayOfD211 fD211;
        
        private IIS.CDLIB.D2 fD2;
        
        // *** Start programmer edit section *** (D21 CustomMembers)

        // *** End programmer edit section *** (D21 CustomMembers)

        
        /// <summary>
        /// D21.
        /// </summary>
        // *** Start programmer edit section *** (D21.D212 CustomAttributes)

        // *** End programmer edit section *** (D21.D212 CustomAttributes)
        public virtual IIS.CDLIB.DetailArrayOfD212 D212
        {
            get
            {
                // *** Start programmer edit section *** (D21.D212 Get start)

                // *** End programmer edit section *** (D21.D212 Get start)
                if ((this.fD212 == null))
                {
                    this.fD212 = new IIS.CDLIB.DetailArrayOfD212(this);
                }
                IIS.CDLIB.DetailArrayOfD212 result = this.fD212;
                // *** Start programmer edit section *** (D21.D212 Get end)

                // *** End programmer edit section *** (D21.D212 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (D21.D212 Set start)

                // *** End programmer edit section *** (D21.D212 Set start)
                this.fD212 = value;
                // *** Start programmer edit section *** (D21.D212 Set end)

                // *** End programmer edit section *** (D21.D212 Set end)
            }
        }
        
        /// <summary>
        /// D21.
        /// </summary>
        // *** Start programmer edit section *** (D21.D213 CustomAttributes)

        // *** End programmer edit section *** (D21.D213 CustomAttributes)
        public virtual IIS.CDLIB.DetailArrayOfD213 D213
        {
            get
            {
                // *** Start programmer edit section *** (D21.D213 Get start)

                // *** End programmer edit section *** (D21.D213 Get start)
                if ((this.fD213 == null))
                {
                    this.fD213 = new IIS.CDLIB.DetailArrayOfD213(this);
                }
                IIS.CDLIB.DetailArrayOfD213 result = this.fD213;
                // *** Start programmer edit section *** (D21.D213 Get end)

                // *** End programmer edit section *** (D21.D213 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (D21.D213 Set start)

                // *** End programmer edit section *** (D21.D213 Set start)
                this.fD213 = value;
                // *** Start programmer edit section *** (D21.D213 Set end)

                // *** End programmer edit section *** (D21.D213 Set end)
            }
        }
        
        /// <summary>
        /// D21.
        /// </summary>
        // *** Start programmer edit section *** (D21.D211 CustomAttributes)

        // *** End programmer edit section *** (D21.D211 CustomAttributes)
        public virtual IIS.CDLIB.DetailArrayOfD211 D211
        {
            get
            {
                // *** Start programmer edit section *** (D21.D211 Get start)

                // *** End programmer edit section *** (D21.D211 Get start)
                if ((this.fD211 == null))
                {
                    this.fD211 = new IIS.CDLIB.DetailArrayOfD211(this);
                }
                IIS.CDLIB.DetailArrayOfD211 result = this.fD211;
                // *** Start programmer edit section *** (D21.D211 Get end)

                // *** End programmer edit section *** (D21.D211 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (D21.D211 Set start)

                // *** End programmer edit section *** (D21.D211 Set start)
                this.fD211 = value;
                // *** Start programmer edit section *** (D21.D211 Set end)

                // *** End programmer edit section *** (D21.D211 Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.CDLIB.D2.
        /// </summary>
        // *** Start programmer edit section *** (D21.D2 CustomAttributes)

        // *** End programmer edit section *** (D21.D2 CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "D2"})]
        public virtual IIS.CDLIB.D2 D2
        {
            get
            {
                // *** Start programmer edit section *** (D21.D2 Get start)

                // *** End programmer edit section *** (D21.D2 Get start)
                IIS.CDLIB.D2 result = this.fD2;
                // *** Start programmer edit section *** (D21.D2 Get end)

                // *** End programmer edit section *** (D21.D2 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (D21.D2 Set start)

                // *** End programmer edit section *** (D21.D2 Set start)
                this.fD2 = value;
                // *** Start programmer edit section *** (D21.D2 Set end)

                // *** End programmer edit section *** (D21.D2 Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "D21_E" view.
            /// </summary>
            public static ICSSoft.STORMNET.View D21_E
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("D21_E", typeof(IIS.CDLIB.D21));
                }
            }
            
            /// <summary>
            /// "FULLD21_E" view.
            /// </summary>
            public static ICSSoft.STORMNET.View FULLD21_E
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("FULLD21_E", typeof(IIS.CDLIB.D21));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of D21.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfD21 CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfD21 CustomAttributes)
    public class DetailArrayOfD21 : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.CDLIB.DetailArrayOfD21 members)

        // *** End programmer edit section *** (IIS.CDLIB.DetailArrayOfD21 members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type D21 by index.
        /// </summary>
        /// <summary>
        /// Adds object with type D21.
        /// </summary>
        public DetailArrayOfD21(IIS.CDLIB.D2 fD2) : 
                base(typeof(D21), ((ICSSoft.STORMNET.DataObject)(fD2)))
        {
        }
        
        public IIS.CDLIB.D21 this[int index]
        {
            get
            {
                return ((IIS.CDLIB.D21)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.CDLIB.D21 dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
