//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CDLIB
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// D22.
    /// </summary>
    // *** Start programmer edit section *** (D22 CustomAttributes)

    // *** End programmer edit section *** (D22 CustomAttributes)
    [AutoAltered()]
    [ICSSoft.STORMNET.NotStored(false)]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("D22_E", new string[] {
            "Name"})]
    [AssociatedDetailViewAttribute("D22_E", "D221", "D_E", true, "", "", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("D22_E", "D222", "D_E", true, "", "", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("D22_E", "D223", "D_E", true, "", "", true, new string[] {
            ""})]
    [View("FULLD22_E", new string[] {
            "*"}, Hidden=new string[] {
            "*"})]
    [AssociatedDetailViewAttribute("FULLD22_E", "D221", "FULLD_E", true, "", "", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("FULLD22_E", "D222", "FULLD_E", true, "", "", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("FULLD22_E", "D223", "FULLD_E", true, "", "", true, new string[] {
            ""})]
    public class D22 : IIS.CDLIB.D
    {
        
        private IIS.CDLIB.DetailArrayOfD222 fD222;
        
        private IIS.CDLIB.DetailArrayOfD221 fD221;
        
        private IIS.CDLIB.DetailArrayOfD223 fD223;
        
        private IIS.CDLIB.D2 fD2;
        
        // *** Start programmer edit section *** (D22 CustomMembers)

        // *** End programmer edit section *** (D22 CustomMembers)

        
        /// <summary>
        /// D22.
        /// </summary>
        // *** Start programmer edit section *** (D22.D222 CustomAttributes)

        // *** End programmer edit section *** (D22.D222 CustomAttributes)
        public virtual IIS.CDLIB.DetailArrayOfD222 D222
        {
            get
            {
                // *** Start programmer edit section *** (D22.D222 Get start)

                // *** End programmer edit section *** (D22.D222 Get start)
                if ((this.fD222 == null))
                {
                    this.fD222 = new IIS.CDLIB.DetailArrayOfD222(this);
                }
                IIS.CDLIB.DetailArrayOfD222 result = this.fD222;
                // *** Start programmer edit section *** (D22.D222 Get end)

                // *** End programmer edit section *** (D22.D222 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (D22.D222 Set start)

                // *** End programmer edit section *** (D22.D222 Set start)
                this.fD222 = value;
                // *** Start programmer edit section *** (D22.D222 Set end)

                // *** End programmer edit section *** (D22.D222 Set end)
            }
        }
        
        /// <summary>
        /// D22.
        /// </summary>
        // *** Start programmer edit section *** (D22.D221 CustomAttributes)

        // *** End programmer edit section *** (D22.D221 CustomAttributes)
        public virtual IIS.CDLIB.DetailArrayOfD221 D221
        {
            get
            {
                // *** Start programmer edit section *** (D22.D221 Get start)

                // *** End programmer edit section *** (D22.D221 Get start)
                if ((this.fD221 == null))
                {
                    this.fD221 = new IIS.CDLIB.DetailArrayOfD221(this);
                }
                IIS.CDLIB.DetailArrayOfD221 result = this.fD221;
                // *** Start programmer edit section *** (D22.D221 Get end)

                // *** End programmer edit section *** (D22.D221 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (D22.D221 Set start)

                // *** End programmer edit section *** (D22.D221 Set start)
                this.fD221 = value;
                // *** Start programmer edit section *** (D22.D221 Set end)

                // *** End programmer edit section *** (D22.D221 Set end)
            }
        }
        
        /// <summary>
        /// D22.
        /// </summary>
        // *** Start programmer edit section *** (D22.D223 CustomAttributes)

        // *** End programmer edit section *** (D22.D223 CustomAttributes)
        public virtual IIS.CDLIB.DetailArrayOfD223 D223
        {
            get
            {
                // *** Start programmer edit section *** (D22.D223 Get start)

                // *** End programmer edit section *** (D22.D223 Get start)
                if ((this.fD223 == null))
                {
                    this.fD223 = new IIS.CDLIB.DetailArrayOfD223(this);
                }
                IIS.CDLIB.DetailArrayOfD223 result = this.fD223;
                // *** Start programmer edit section *** (D22.D223 Get end)

                // *** End programmer edit section *** (D22.D223 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (D22.D223 Set start)

                // *** End programmer edit section *** (D22.D223 Set start)
                this.fD223 = value;
                // *** Start programmer edit section *** (D22.D223 Set end)

                // *** End programmer edit section *** (D22.D223 Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.CDLIB.D2.
        /// </summary>
        // *** Start programmer edit section *** (D22.D2 CustomAttributes)

        // *** End programmer edit section *** (D22.D2 CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "D2"})]
        public virtual IIS.CDLIB.D2 D2
        {
            get
            {
                // *** Start programmer edit section *** (D22.D2 Get start)

                // *** End programmer edit section *** (D22.D2 Get start)
                IIS.CDLIB.D2 result = this.fD2;
                // *** Start programmer edit section *** (D22.D2 Get end)

                // *** End programmer edit section *** (D22.D2 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (D22.D2 Set start)

                // *** End programmer edit section *** (D22.D2 Set start)
                this.fD2 = value;
                // *** Start programmer edit section *** (D22.D2 Set end)

                // *** End programmer edit section *** (D22.D2 Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "D22_E" view.
            /// </summary>
            public static ICSSoft.STORMNET.View D22_E
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("D22_E", typeof(IIS.CDLIB.D22));
                }
            }
            
            /// <summary>
            /// "FULLD22_E" view.
            /// </summary>
            public static ICSSoft.STORMNET.View FULLD22_E
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("FULLD22_E", typeof(IIS.CDLIB.D22));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of D22.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfD22 CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfD22 CustomAttributes)
    public class DetailArrayOfD22 : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.CDLIB.DetailArrayOfD22 members)

        // *** End programmer edit section *** (IIS.CDLIB.DetailArrayOfD22 members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type D22 by index.
        /// </summary>
        /// <summary>
        /// Adds object with type D22.
        /// </summary>
        public DetailArrayOfD22(IIS.CDLIB.D2 fD2) : 
                base(typeof(D22), ((ICSSoft.STORMNET.DataObject)(fD2)))
        {
        }
        
        public IIS.CDLIB.D22 this[int index]
        {
            get
            {
                return ((IIS.CDLIB.D22)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.CDLIB.D22 dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
