//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CDLIB
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// D223.
    /// </summary>
    // *** Start programmer edit section *** (D223 CustomAttributes)

    // *** End programmer edit section *** (D223 CustomAttributes)
    [AutoAltered()]
    [ICSSoft.STORMNET.NotStored(false)]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class D223 : IIS.CDLIB.D
    {
        
        private IIS.CDLIB.D22 fD22;
        
        // *** Start programmer edit section *** (D223 CustomMembers)

        // *** End programmer edit section *** (D223 CustomMembers)

        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.CDLIB.D22.
        /// </summary>
        // *** Start programmer edit section *** (D223.D22 CustomAttributes)

        // *** End programmer edit section *** (D223.D22 CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "D22"})]
        public virtual IIS.CDLIB.D22 D22
        {
            get
            {
                // *** Start programmer edit section *** (D223.D22 Get start)

                // *** End programmer edit section *** (D223.D22 Get start)
                IIS.CDLIB.D22 result = this.fD22;
                // *** Start programmer edit section *** (D223.D22 Get end)

                // *** End programmer edit section *** (D223.D22 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (D223.D22 Set start)

                // *** End programmer edit section *** (D223.D22 Set start)
                this.fD22 = value;
                // *** Start programmer edit section *** (D223.D22 Set end)

                // *** End programmer edit section *** (D223.D22 Set end)
            }
        }
    }
    
    /// <summary>
    /// Detail array of D223.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfD223 CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfD223 CustomAttributes)
    public class DetailArrayOfD223 : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.CDLIB.DetailArrayOfD223 members)

        // *** End programmer edit section *** (IIS.CDLIB.DetailArrayOfD223 members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type D223 by index.
        /// </summary>
        /// <summary>
        /// Adds object with type D223.
        /// </summary>
        public DetailArrayOfD223(IIS.CDLIB.D22 fD22) : 
                base(typeof(D223), ((ICSSoft.STORMNET.DataObject)(fD22)))
        {
        }
        
        public IIS.CDLIB.D223 this[int index]
        {
            get
            {
                return ((IIS.CDLIB.D223)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.CDLIB.D223 dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
