//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CDLIB
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// D23.
    /// </summary>
    // *** Start programmer edit section *** (D23 CustomAttributes)

    // *** End programmer edit section *** (D23 CustomAttributes)
    [AutoAltered()]
    [ICSSoft.STORMNET.NotStored(false)]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("D23_E", new string[] {
            "Name"})]
    [AssociatedDetailViewAttribute("D23_E", "D231", "D_E", true, "", "", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("D23_E", "D232", "D_E", true, "", "", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("D23_E", "D233", "D_E", true, "", "", true, new string[] {
            ""})]
    [View("FULLD23_E", new string[] {
            "*"}, Hidden=new string[] {
            "*"})]
    [AssociatedDetailViewAttribute("FULLD23_E", "D231", "FULLD_E", true, "", "", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("FULLD23_E", "D232", "FULLD_E", true, "", "", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("FULLD23_E", "D233", "FULLD_E", true, "", "", true, new string[] {
            ""})]
    public class D23 : IIS.CDLIB.D
    {
        
        private IIS.CDLIB.DetailArrayOfD232 fD232;
        
        private IIS.CDLIB.DetailArrayOfD231 fD231;
        
        private IIS.CDLIB.DetailArrayOfD233 fD233;
        
        private IIS.CDLIB.D2 fD2;
        
        // *** Start programmer edit section *** (D23 CustomMembers)

        // *** End programmer edit section *** (D23 CustomMembers)

        
        /// <summary>
        /// D23.
        /// </summary>
        // *** Start programmer edit section *** (D23.D232 CustomAttributes)

        // *** End programmer edit section *** (D23.D232 CustomAttributes)
        public virtual IIS.CDLIB.DetailArrayOfD232 D232
        {
            get
            {
                // *** Start programmer edit section *** (D23.D232 Get start)

                // *** End programmer edit section *** (D23.D232 Get start)
                if ((this.fD232 == null))
                {
                    this.fD232 = new IIS.CDLIB.DetailArrayOfD232(this);
                }
                IIS.CDLIB.DetailArrayOfD232 result = this.fD232;
                // *** Start programmer edit section *** (D23.D232 Get end)

                // *** End programmer edit section *** (D23.D232 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (D23.D232 Set start)

                // *** End programmer edit section *** (D23.D232 Set start)
                this.fD232 = value;
                // *** Start programmer edit section *** (D23.D232 Set end)

                // *** End programmer edit section *** (D23.D232 Set end)
            }
        }
        
        /// <summary>
        /// D23.
        /// </summary>
        // *** Start programmer edit section *** (D23.D231 CustomAttributes)

        // *** End programmer edit section *** (D23.D231 CustomAttributes)
        public virtual IIS.CDLIB.DetailArrayOfD231 D231
        {
            get
            {
                // *** Start programmer edit section *** (D23.D231 Get start)

                // *** End programmer edit section *** (D23.D231 Get start)
                if ((this.fD231 == null))
                {
                    this.fD231 = new IIS.CDLIB.DetailArrayOfD231(this);
                }
                IIS.CDLIB.DetailArrayOfD231 result = this.fD231;
                // *** Start programmer edit section *** (D23.D231 Get end)

                // *** End programmer edit section *** (D23.D231 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (D23.D231 Set start)

                // *** End programmer edit section *** (D23.D231 Set start)
                this.fD231 = value;
                // *** Start programmer edit section *** (D23.D231 Set end)

                // *** End programmer edit section *** (D23.D231 Set end)
            }
        }
        
        /// <summary>
        /// D23.
        /// </summary>
        // *** Start programmer edit section *** (D23.D233 CustomAttributes)

        // *** End programmer edit section *** (D23.D233 CustomAttributes)
        public virtual IIS.CDLIB.DetailArrayOfD233 D233
        {
            get
            {
                // *** Start programmer edit section *** (D23.D233 Get start)

                // *** End programmer edit section *** (D23.D233 Get start)
                if ((this.fD233 == null))
                {
                    this.fD233 = new IIS.CDLIB.DetailArrayOfD233(this);
                }
                IIS.CDLIB.DetailArrayOfD233 result = this.fD233;
                // *** Start programmer edit section *** (D23.D233 Get end)

                // *** End programmer edit section *** (D23.D233 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (D23.D233 Set start)

                // *** End programmer edit section *** (D23.D233 Set start)
                this.fD233 = value;
                // *** Start programmer edit section *** (D23.D233 Set end)

                // *** End programmer edit section *** (D23.D233 Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.CDLIB.D2.
        /// </summary>
        // *** Start programmer edit section *** (D23.D2 CustomAttributes)

        // *** End programmer edit section *** (D23.D2 CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "D2"})]
        public virtual IIS.CDLIB.D2 D2
        {
            get
            {
                // *** Start programmer edit section *** (D23.D2 Get start)

                // *** End programmer edit section *** (D23.D2 Get start)
                IIS.CDLIB.D2 result = this.fD2;
                // *** Start programmer edit section *** (D23.D2 Get end)

                // *** End programmer edit section *** (D23.D2 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (D23.D2 Set start)

                // *** End programmer edit section *** (D23.D2 Set start)
                this.fD2 = value;
                // *** Start programmer edit section *** (D23.D2 Set end)

                // *** End programmer edit section *** (D23.D2 Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "D23_E" view.
            /// </summary>
            public static ICSSoft.STORMNET.View D23_E
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("D23_E", typeof(IIS.CDLIB.D23));
                }
            }
            
            /// <summary>
            /// "FULLD23_E" view.
            /// </summary>
            public static ICSSoft.STORMNET.View FULLD23_E
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("FULLD23_E", typeof(IIS.CDLIB.D23));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of D23.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfD23 CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfD23 CustomAttributes)
    public class DetailArrayOfD23 : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.CDLIB.DetailArrayOfD23 members)

        // *** End programmer edit section *** (IIS.CDLIB.DetailArrayOfD23 members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type D23 by index.
        /// </summary>
        /// <summary>
        /// Adds object with type D23.
        /// </summary>
        public DetailArrayOfD23(IIS.CDLIB.D2 fD2) : 
                base(typeof(D23), ((ICSSoft.STORMNET.DataObject)(fD2)))
        {
        }
        
        public IIS.CDLIB.D23 this[int index]
        {
            get
            {
                return ((IIS.CDLIB.D23)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.CDLIB.D23 dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
