//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CDLIB
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// D231.
    /// </summary>
    // *** Start programmer edit section *** (D231 CustomAttributes)

    // *** End programmer edit section *** (D231 CustomAttributes)
    [AutoAltered()]
    [ICSSoft.STORMNET.NotStored(false)]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class D231 : IIS.CDLIB.D
    {
        
        private IIS.CDLIB.D23 fD23;
        
        // *** Start programmer edit section *** (D231 CustomMembers)

        // *** End programmer edit section *** (D231 CustomMembers)

        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.CDLIB.D23.
        /// </summary>
        // *** Start programmer edit section *** (D231.D23 CustomAttributes)

        // *** End programmer edit section *** (D231.D23 CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "D23"})]
        public virtual IIS.CDLIB.D23 D23
        {
            get
            {
                // *** Start programmer edit section *** (D231.D23 Get start)

                // *** End programmer edit section *** (D231.D23 Get start)
                IIS.CDLIB.D23 result = this.fD23;
                // *** Start programmer edit section *** (D231.D23 Get end)

                // *** End programmer edit section *** (D231.D23 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (D231.D23 Set start)

                // *** End programmer edit section *** (D231.D23 Set start)
                this.fD23 = value;
                // *** Start programmer edit section *** (D231.D23 Set end)

                // *** End programmer edit section *** (D231.D23 Set end)
            }
        }
    }
    
    /// <summary>
    /// Detail array of D231.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfD231 CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfD231 CustomAttributes)
    public class DetailArrayOfD231 : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.CDLIB.DetailArrayOfD231 members)

        // *** End programmer edit section *** (IIS.CDLIB.DetailArrayOfD231 members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type D231 by index.
        /// </summary>
        /// <summary>
        /// Adds object with type D231.
        /// </summary>
        public DetailArrayOfD231(IIS.CDLIB.D23 fD23) : 
                base(typeof(D231), ((ICSSoft.STORMNET.DataObject)(fD23)))
        {
        }
        
        public IIS.CDLIB.D231 this[int index]
        {
            get
            {
                return ((IIS.CDLIB.D231)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.CDLIB.D231 dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
