//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CDLIB
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// D3.
    /// </summary>
    // *** Start programmer edit section *** (D3 CustomAttributes)

    // *** End programmer edit section *** (D3 CustomAttributes)
    [AutoAltered()]
    [ICSSoft.STORMNET.NotStored(false)]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("D3_E", new string[] {
            "Name"})]
    [AssociatedDetailViewAttribute("D3_E", "D31", "D31_E", true, "", "", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("D3_E", "D32", "D32_E", true, "", "", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("D3_E", "D33", "D33_E", true, "", "", true, new string[] {
            ""})]
    [View("FULLD3_E", new string[] {
            "*"}, Hidden=new string[] {
            "*"})]
    [AssociatedDetailViewAttribute("FULLD3_E", "D31", "FULLD31_E", true, "", "", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("FULLD3_E", "D32", "FULLD32_E", true, "", "", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("FULLD3_E", "D33", "FULLD33_E", true, "", "", true, new string[] {
            ""})]
    public class D3 : IIS.CDLIB.D
    {
        
        private IIS.CDLIB.DetailArrayOfD32 fD32;
        
        private IIS.CDLIB.DetailArrayOfD31 fD31;
        
        private IIS.CDLIB.DetailArrayOfD33 fD33;
        
        private IIS.CDLIB.D0 fD0;
        
        // *** Start programmer edit section *** (D3 CustomMembers)

        // *** End programmer edit section *** (D3 CustomMembers)

        
        /// <summary>
        /// D3.
        /// </summary>
        // *** Start programmer edit section *** (D3.D32 CustomAttributes)

        // *** End programmer edit section *** (D3.D32 CustomAttributes)
        public virtual IIS.CDLIB.DetailArrayOfD32 D32
        {
            get
            {
                // *** Start programmer edit section *** (D3.D32 Get start)

                // *** End programmer edit section *** (D3.D32 Get start)
                if ((this.fD32 == null))
                {
                    this.fD32 = new IIS.CDLIB.DetailArrayOfD32(this);
                }
                IIS.CDLIB.DetailArrayOfD32 result = this.fD32;
                // *** Start programmer edit section *** (D3.D32 Get end)

                // *** End programmer edit section *** (D3.D32 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (D3.D32 Set start)

                // *** End programmer edit section *** (D3.D32 Set start)
                this.fD32 = value;
                // *** Start programmer edit section *** (D3.D32 Set end)

                // *** End programmer edit section *** (D3.D32 Set end)
            }
        }
        
        /// <summary>
        /// D3.
        /// </summary>
        // *** Start programmer edit section *** (D3.D31 CustomAttributes)

        // *** End programmer edit section *** (D3.D31 CustomAttributes)
        public virtual IIS.CDLIB.DetailArrayOfD31 D31
        {
            get
            {
                // *** Start programmer edit section *** (D3.D31 Get start)

                // *** End programmer edit section *** (D3.D31 Get start)
                if ((this.fD31 == null))
                {
                    this.fD31 = new IIS.CDLIB.DetailArrayOfD31(this);
                }
                IIS.CDLIB.DetailArrayOfD31 result = this.fD31;
                // *** Start programmer edit section *** (D3.D31 Get end)

                // *** End programmer edit section *** (D3.D31 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (D3.D31 Set start)

                // *** End programmer edit section *** (D3.D31 Set start)
                this.fD31 = value;
                // *** Start programmer edit section *** (D3.D31 Set end)

                // *** End programmer edit section *** (D3.D31 Set end)
            }
        }
        
        /// <summary>
        /// D3.
        /// </summary>
        // *** Start programmer edit section *** (D3.D33 CustomAttributes)

        // *** End programmer edit section *** (D3.D33 CustomAttributes)
        public virtual IIS.CDLIB.DetailArrayOfD33 D33
        {
            get
            {
                // *** Start programmer edit section *** (D3.D33 Get start)

                // *** End programmer edit section *** (D3.D33 Get start)
                if ((this.fD33 == null))
                {
                    this.fD33 = new IIS.CDLIB.DetailArrayOfD33(this);
                }
                IIS.CDLIB.DetailArrayOfD33 result = this.fD33;
                // *** Start programmer edit section *** (D3.D33 Get end)

                // *** End programmer edit section *** (D3.D33 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (D3.D33 Set start)

                // *** End programmer edit section *** (D3.D33 Set start)
                this.fD33 = value;
                // *** Start programmer edit section *** (D3.D33 Set end)

                // *** End programmer edit section *** (D3.D33 Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.CDLIB.D0.
        /// </summary>
        // *** Start programmer edit section *** (D3.D0 CustomAttributes)

        // *** End programmer edit section *** (D3.D0 CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "D0"})]
        public virtual IIS.CDLIB.D0 D0
        {
            get
            {
                // *** Start programmer edit section *** (D3.D0 Get start)

                // *** End programmer edit section *** (D3.D0 Get start)
                IIS.CDLIB.D0 result = this.fD0;
                // *** Start programmer edit section *** (D3.D0 Get end)

                // *** End programmer edit section *** (D3.D0 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (D3.D0 Set start)

                // *** End programmer edit section *** (D3.D0 Set start)
                this.fD0 = value;
                // *** Start programmer edit section *** (D3.D0 Set end)

                // *** End programmer edit section *** (D3.D0 Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "D3_E" view.
            /// </summary>
            public static ICSSoft.STORMNET.View D3_E
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("D3_E", typeof(IIS.CDLIB.D3));
                }
            }
            
            /// <summary>
            /// "FULLD3_E" view.
            /// </summary>
            public static ICSSoft.STORMNET.View FULLD3_E
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("FULLD3_E", typeof(IIS.CDLIB.D3));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of D3.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfD3 CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfD3 CustomAttributes)
    public class DetailArrayOfD3 : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.CDLIB.DetailArrayOfD3 members)

        // *** End programmer edit section *** (IIS.CDLIB.DetailArrayOfD3 members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type D3 by index.
        /// </summary>
        /// <summary>
        /// Adds object with type D3.
        /// </summary>
        public DetailArrayOfD3(IIS.CDLIB.D0 fD0) : 
                base(typeof(D3), ((ICSSoft.STORMNET.DataObject)(fD0)))
        {
        }
        
        public IIS.CDLIB.D3 this[int index]
        {
            get
            {
                return ((IIS.CDLIB.D3)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.CDLIB.D3 dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
