//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CDLIB
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// D31.
    /// </summary>
    // *** Start programmer edit section *** (D31 CustomAttributes)

    // *** End programmer edit section *** (D31 CustomAttributes)
    [AutoAltered()]
    [ICSSoft.STORMNET.NotStored(false)]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("D31_E", new string[] {
            "Name"})]
    [AssociatedDetailViewAttribute("D31_E", "D311", "D_E", true, "", "", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("D31_E", "D312", "D_E", true, "", "", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("D31_E", "D313", "D_E", true, "", "", true, new string[] {
            ""})]
    [View("FULLD31_E", new string[] {
            "*"}, Hidden=new string[] {
            "*"})]
    [AssociatedDetailViewAttribute("FULLD31_E", "D311", "FULLD_E", true, "", "", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("FULLD31_E", "D312", "FULLD_E", true, "", "", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("FULLD31_E", "D313", "FULLD_E", true, "", "", true, new string[] {
            ""})]
    public class D31 : IIS.CDLIB.D
    {
        
        private IIS.CDLIB.DetailArrayOfD311 fD311;
        
        private IIS.CDLIB.DetailArrayOfD313 fD313;
        
        private IIS.CDLIB.DetailArrayOfD312 fD312;
        
        private IIS.CDLIB.D3 fD3;
        
        // *** Start programmer edit section *** (D31 CustomMembers)

        // *** End programmer edit section *** (D31 CustomMembers)

        
        /// <summary>
        /// D31.
        /// </summary>
        // *** Start programmer edit section *** (D31.D311 CustomAttributes)

        // *** End programmer edit section *** (D31.D311 CustomAttributes)
        public virtual IIS.CDLIB.DetailArrayOfD311 D311
        {
            get
            {
                // *** Start programmer edit section *** (D31.D311 Get start)

                // *** End programmer edit section *** (D31.D311 Get start)
                if ((this.fD311 == null))
                {
                    this.fD311 = new IIS.CDLIB.DetailArrayOfD311(this);
                }
                IIS.CDLIB.DetailArrayOfD311 result = this.fD311;
                // *** Start programmer edit section *** (D31.D311 Get end)

                // *** End programmer edit section *** (D31.D311 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (D31.D311 Set start)

                // *** End programmer edit section *** (D31.D311 Set start)
                this.fD311 = value;
                // *** Start programmer edit section *** (D31.D311 Set end)

                // *** End programmer edit section *** (D31.D311 Set end)
            }
        }
        
        /// <summary>
        /// D31.
        /// </summary>
        // *** Start programmer edit section *** (D31.D313 CustomAttributes)

        // *** End programmer edit section *** (D31.D313 CustomAttributes)
        public virtual IIS.CDLIB.DetailArrayOfD313 D313
        {
            get
            {
                // *** Start programmer edit section *** (D31.D313 Get start)

                // *** End programmer edit section *** (D31.D313 Get start)
                if ((this.fD313 == null))
                {
                    this.fD313 = new IIS.CDLIB.DetailArrayOfD313(this);
                }
                IIS.CDLIB.DetailArrayOfD313 result = this.fD313;
                // *** Start programmer edit section *** (D31.D313 Get end)

                // *** End programmer edit section *** (D31.D313 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (D31.D313 Set start)

                // *** End programmer edit section *** (D31.D313 Set start)
                this.fD313 = value;
                // *** Start programmer edit section *** (D31.D313 Set end)

                // *** End programmer edit section *** (D31.D313 Set end)
            }
        }
        
        /// <summary>
        /// D31.
        /// </summary>
        // *** Start programmer edit section *** (D31.D312 CustomAttributes)

        // *** End programmer edit section *** (D31.D312 CustomAttributes)
        public virtual IIS.CDLIB.DetailArrayOfD312 D312
        {
            get
            {
                // *** Start programmer edit section *** (D31.D312 Get start)

                // *** End programmer edit section *** (D31.D312 Get start)
                if ((this.fD312 == null))
                {
                    this.fD312 = new IIS.CDLIB.DetailArrayOfD312(this);
                }
                IIS.CDLIB.DetailArrayOfD312 result = this.fD312;
                // *** Start programmer edit section *** (D31.D312 Get end)

                // *** End programmer edit section *** (D31.D312 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (D31.D312 Set start)

                // *** End programmer edit section *** (D31.D312 Set start)
                this.fD312 = value;
                // *** Start programmer edit section *** (D31.D312 Set end)

                // *** End programmer edit section *** (D31.D312 Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.CDLIB.D3.
        /// </summary>
        // *** Start programmer edit section *** (D31.D3 CustomAttributes)

        // *** End programmer edit section *** (D31.D3 CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "D3"})]
        public virtual IIS.CDLIB.D3 D3
        {
            get
            {
                // *** Start programmer edit section *** (D31.D3 Get start)

                // *** End programmer edit section *** (D31.D3 Get start)
                IIS.CDLIB.D3 result = this.fD3;
                // *** Start programmer edit section *** (D31.D3 Get end)

                // *** End programmer edit section *** (D31.D3 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (D31.D3 Set start)

                // *** End programmer edit section *** (D31.D3 Set start)
                this.fD3 = value;
                // *** Start programmer edit section *** (D31.D3 Set end)

                // *** End programmer edit section *** (D31.D3 Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "D31_E" view.
            /// </summary>
            public static ICSSoft.STORMNET.View D31_E
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("D31_E", typeof(IIS.CDLIB.D31));
                }
            }
            
            /// <summary>
            /// "FULLD31_E" view.
            /// </summary>
            public static ICSSoft.STORMNET.View FULLD31_E
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("FULLD31_E", typeof(IIS.CDLIB.D31));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of D31.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfD31 CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfD31 CustomAttributes)
    public class DetailArrayOfD31 : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.CDLIB.DetailArrayOfD31 members)

        // *** End programmer edit section *** (IIS.CDLIB.DetailArrayOfD31 members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type D31 by index.
        /// </summary>
        /// <summary>
        /// Adds object with type D31.
        /// </summary>
        public DetailArrayOfD31(IIS.CDLIB.D3 fD3) : 
                base(typeof(D31), ((ICSSoft.STORMNET.DataObject)(fD3)))
        {
        }
        
        public IIS.CDLIB.D31 this[int index]
        {
            get
            {
                return ((IIS.CDLIB.D31)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.CDLIB.D31 dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
