//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CDLIB
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// D32.
    /// </summary>
    // *** Start programmer edit section *** (D32 CustomAttributes)

    // *** End programmer edit section *** (D32 CustomAttributes)
    [AutoAltered()]
    [ICSSoft.STORMNET.NotStored(false)]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("D32_E", new string[] {
            "Name"})]
    [AssociatedDetailViewAttribute("D32_E", "D321", "D_E", true, "", "", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("D32_E", "D322", "D_E", true, "", "", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("D32_E", "D323", "D_E", true, "", "", true, new string[] {
            ""})]
    [View("FULLD32_E", new string[] {
            "*"}, Hidden=new string[] {
            "*"})]
    [AssociatedDetailViewAttribute("FULLD32_E", "D321", "FULLD_E", true, "", "", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("FULLD32_E", "D322", "FULLD_E", true, "", "", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("FULLD32_E", "D323", "FULLD_E", true, "", "", true, new string[] {
            ""})]
    public class D32 : IIS.CDLIB.D
    {
        
        private IIS.CDLIB.DetailArrayOfD322 fD322;
        
        private IIS.CDLIB.DetailArrayOfD323 fD323;
        
        private IIS.CDLIB.DetailArrayOfD321 fD321;
        
        private IIS.CDLIB.D3 fD3;
        
        // *** Start programmer edit section *** (D32 CustomMembers)

        // *** End programmer edit section *** (D32 CustomMembers)

        
        /// <summary>
        /// D32.
        /// </summary>
        // *** Start programmer edit section *** (D32.D322 CustomAttributes)

        // *** End programmer edit section *** (D32.D322 CustomAttributes)
        public virtual IIS.CDLIB.DetailArrayOfD322 D322
        {
            get
            {
                // *** Start programmer edit section *** (D32.D322 Get start)

                // *** End programmer edit section *** (D32.D322 Get start)
                if ((this.fD322 == null))
                {
                    this.fD322 = new IIS.CDLIB.DetailArrayOfD322(this);
                }
                IIS.CDLIB.DetailArrayOfD322 result = this.fD322;
                // *** Start programmer edit section *** (D32.D322 Get end)

                // *** End programmer edit section *** (D32.D322 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (D32.D322 Set start)

                // *** End programmer edit section *** (D32.D322 Set start)
                this.fD322 = value;
                // *** Start programmer edit section *** (D32.D322 Set end)

                // *** End programmer edit section *** (D32.D322 Set end)
            }
        }
        
        /// <summary>
        /// D32.
        /// </summary>
        // *** Start programmer edit section *** (D32.D323 CustomAttributes)

        // *** End programmer edit section *** (D32.D323 CustomAttributes)
        public virtual IIS.CDLIB.DetailArrayOfD323 D323
        {
            get
            {
                // *** Start programmer edit section *** (D32.D323 Get start)

                // *** End programmer edit section *** (D32.D323 Get start)
                if ((this.fD323 == null))
                {
                    this.fD323 = new IIS.CDLIB.DetailArrayOfD323(this);
                }
                IIS.CDLIB.DetailArrayOfD323 result = this.fD323;
                // *** Start programmer edit section *** (D32.D323 Get end)

                // *** End programmer edit section *** (D32.D323 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (D32.D323 Set start)

                // *** End programmer edit section *** (D32.D323 Set start)
                this.fD323 = value;
                // *** Start programmer edit section *** (D32.D323 Set end)

                // *** End programmer edit section *** (D32.D323 Set end)
            }
        }
        
        /// <summary>
        /// D32.
        /// </summary>
        // *** Start programmer edit section *** (D32.D321 CustomAttributes)

        // *** End programmer edit section *** (D32.D321 CustomAttributes)
        public virtual IIS.CDLIB.DetailArrayOfD321 D321
        {
            get
            {
                // *** Start programmer edit section *** (D32.D321 Get start)

                // *** End programmer edit section *** (D32.D321 Get start)
                if ((this.fD321 == null))
                {
                    this.fD321 = new IIS.CDLIB.DetailArrayOfD321(this);
                }
                IIS.CDLIB.DetailArrayOfD321 result = this.fD321;
                // *** Start programmer edit section *** (D32.D321 Get end)

                // *** End programmer edit section *** (D32.D321 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (D32.D321 Set start)

                // *** End programmer edit section *** (D32.D321 Set start)
                this.fD321 = value;
                // *** Start programmer edit section *** (D32.D321 Set end)

                // *** End programmer edit section *** (D32.D321 Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.CDLIB.D3.
        /// </summary>
        // *** Start programmer edit section *** (D32.D3 CustomAttributes)

        // *** End programmer edit section *** (D32.D3 CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "D3"})]
        public virtual IIS.CDLIB.D3 D3
        {
            get
            {
                // *** Start programmer edit section *** (D32.D3 Get start)

                // *** End programmer edit section *** (D32.D3 Get start)
                IIS.CDLIB.D3 result = this.fD3;
                // *** Start programmer edit section *** (D32.D3 Get end)

                // *** End programmer edit section *** (D32.D3 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (D32.D3 Set start)

                // *** End programmer edit section *** (D32.D3 Set start)
                this.fD3 = value;
                // *** Start programmer edit section *** (D32.D3 Set end)

                // *** End programmer edit section *** (D32.D3 Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "D32_E" view.
            /// </summary>
            public static ICSSoft.STORMNET.View D32_E
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("D32_E", typeof(IIS.CDLIB.D32));
                }
            }
            
            /// <summary>
            /// "FULLD32_E" view.
            /// </summary>
            public static ICSSoft.STORMNET.View FULLD32_E
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("FULLD32_E", typeof(IIS.CDLIB.D32));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of D32.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfD32 CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfD32 CustomAttributes)
    public class DetailArrayOfD32 : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.CDLIB.DetailArrayOfD32 members)

        // *** End programmer edit section *** (IIS.CDLIB.DetailArrayOfD32 members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type D32 by index.
        /// </summary>
        /// <summary>
        /// Adds object with type D32.
        /// </summary>
        public DetailArrayOfD32(IIS.CDLIB.D3 fD3) : 
                base(typeof(D32), ((ICSSoft.STORMNET.DataObject)(fD3)))
        {
        }
        
        public IIS.CDLIB.D32 this[int index]
        {
            get
            {
                return ((IIS.CDLIB.D32)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.CDLIB.D32 dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
