//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CDLIB
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// D323.
    /// </summary>
    // *** Start programmer edit section *** (D323 CustomAttributes)

    // *** End programmer edit section *** (D323 CustomAttributes)
    [AutoAltered()]
    [ICSSoft.STORMNET.NotStored(false)]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class D323 : IIS.CDLIB.D
    {
        
        private IIS.CDLIB.D32 fD32;
        
        // *** Start programmer edit section *** (D323 CustomMembers)

        // *** End programmer edit section *** (D323 CustomMembers)

        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.CDLIB.D32.
        /// </summary>
        // *** Start programmer edit section *** (D323.D32 CustomAttributes)

        // *** End programmer edit section *** (D323.D32 CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "D32"})]
        public virtual IIS.CDLIB.D32 D32
        {
            get
            {
                // *** Start programmer edit section *** (D323.D32 Get start)

                // *** End programmer edit section *** (D323.D32 Get start)
                IIS.CDLIB.D32 result = this.fD32;
                // *** Start programmer edit section *** (D323.D32 Get end)

                // *** End programmer edit section *** (D323.D32 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (D323.D32 Set start)

                // *** End programmer edit section *** (D323.D32 Set start)
                this.fD32 = value;
                // *** Start programmer edit section *** (D323.D32 Set end)

                // *** End programmer edit section *** (D323.D32 Set end)
            }
        }
    }
    
    /// <summary>
    /// Detail array of D323.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfD323 CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfD323 CustomAttributes)
    public class DetailArrayOfD323 : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.CDLIB.DetailArrayOfD323 members)

        // *** End programmer edit section *** (IIS.CDLIB.DetailArrayOfD323 members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type D323 by index.
        /// </summary>
        /// <summary>
        /// Adds object with type D323.
        /// </summary>
        public DetailArrayOfD323(IIS.CDLIB.D32 fD32) : 
                base(typeof(D323), ((ICSSoft.STORMNET.DataObject)(fD32)))
        {
        }
        
        public IIS.CDLIB.D323 this[int index]
        {
            get
            {
                return ((IIS.CDLIB.D323)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.CDLIB.D323 dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
