//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CDLIB
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// D33.
    /// </summary>
    // *** Start programmer edit section *** (D33 CustomAttributes)

    // *** End programmer edit section *** (D33 CustomAttributes)
    [AutoAltered()]
    [ICSSoft.STORMNET.NotStored(false)]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("D33_E", new string[] {
            "Name"})]
    [AssociatedDetailViewAttribute("D33_E", "D331", "D_E", true, "", "", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("D33_E", "D332", "D_E", true, "", "", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("D33_E", "D333", "D_E", true, "", "", true, new string[] {
            ""})]
    [View("FULLD33_E", new string[] {
            "*"}, Hidden=new string[] {
            "*"})]
    [AssociatedDetailViewAttribute("FULLD33_E", "D331", "FULLD_E", true, "", "", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("FULLD33_E", "D332", "FULLD_E", true, "", "", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("FULLD33_E", "D333", "FULLD_E", true, "", "", true, new string[] {
            ""})]
    public class D33 : IIS.CDLIB.D
    {
        
        private IIS.CDLIB.DetailArrayOfD333 fD333;
        
        private IIS.CDLIB.DetailArrayOfD331 fD331;
        
        private IIS.CDLIB.DetailArrayOfD332 fD332;
        
        private IIS.CDLIB.D3 fD3;
        
        // *** Start programmer edit section *** (D33 CustomMembers)

        // *** End programmer edit section *** (D33 CustomMembers)

        
        /// <summary>
        /// D33.
        /// </summary>
        // *** Start programmer edit section *** (D33.D333 CustomAttributes)

        // *** End programmer edit section *** (D33.D333 CustomAttributes)
        public virtual IIS.CDLIB.DetailArrayOfD333 D333
        {
            get
            {
                // *** Start programmer edit section *** (D33.D333 Get start)

                // *** End programmer edit section *** (D33.D333 Get start)
                if ((this.fD333 == null))
                {
                    this.fD333 = new IIS.CDLIB.DetailArrayOfD333(this);
                }
                IIS.CDLIB.DetailArrayOfD333 result = this.fD333;
                // *** Start programmer edit section *** (D33.D333 Get end)

                // *** End programmer edit section *** (D33.D333 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (D33.D333 Set start)

                // *** End programmer edit section *** (D33.D333 Set start)
                this.fD333 = value;
                // *** Start programmer edit section *** (D33.D333 Set end)

                // *** End programmer edit section *** (D33.D333 Set end)
            }
        }
        
        /// <summary>
        /// D33.
        /// </summary>
        // *** Start programmer edit section *** (D33.D331 CustomAttributes)

        // *** End programmer edit section *** (D33.D331 CustomAttributes)
        public virtual IIS.CDLIB.DetailArrayOfD331 D331
        {
            get
            {
                // *** Start programmer edit section *** (D33.D331 Get start)

                // *** End programmer edit section *** (D33.D331 Get start)
                if ((this.fD331 == null))
                {
                    this.fD331 = new IIS.CDLIB.DetailArrayOfD331(this);
                }
                IIS.CDLIB.DetailArrayOfD331 result = this.fD331;
                // *** Start programmer edit section *** (D33.D331 Get end)

                // *** End programmer edit section *** (D33.D331 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (D33.D331 Set start)

                // *** End programmer edit section *** (D33.D331 Set start)
                this.fD331 = value;
                // *** Start programmer edit section *** (D33.D331 Set end)

                // *** End programmer edit section *** (D33.D331 Set end)
            }
        }
        
        /// <summary>
        /// D33.
        /// </summary>
        // *** Start programmer edit section *** (D33.D332 CustomAttributes)

        // *** End programmer edit section *** (D33.D332 CustomAttributes)
        public virtual IIS.CDLIB.DetailArrayOfD332 D332
        {
            get
            {
                // *** Start programmer edit section *** (D33.D332 Get start)

                // *** End programmer edit section *** (D33.D332 Get start)
                if ((this.fD332 == null))
                {
                    this.fD332 = new IIS.CDLIB.DetailArrayOfD332(this);
                }
                IIS.CDLIB.DetailArrayOfD332 result = this.fD332;
                // *** Start programmer edit section *** (D33.D332 Get end)

                // *** End programmer edit section *** (D33.D332 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (D33.D332 Set start)

                // *** End programmer edit section *** (D33.D332 Set start)
                this.fD332 = value;
                // *** Start programmer edit section *** (D33.D332 Set end)

                // *** End programmer edit section *** (D33.D332 Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.CDLIB.D3.
        /// </summary>
        // *** Start programmer edit section *** (D33.D3 CustomAttributes)

        // *** End programmer edit section *** (D33.D3 CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "D3"})]
        public virtual IIS.CDLIB.D3 D3
        {
            get
            {
                // *** Start programmer edit section *** (D33.D3 Get start)

                // *** End programmer edit section *** (D33.D3 Get start)
                IIS.CDLIB.D3 result = this.fD3;
                // *** Start programmer edit section *** (D33.D3 Get end)

                // *** End programmer edit section *** (D33.D3 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (D33.D3 Set start)

                // *** End programmer edit section *** (D33.D3 Set start)
                this.fD3 = value;
                // *** Start programmer edit section *** (D33.D3 Set end)

                // *** End programmer edit section *** (D33.D3 Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "D33_E" view.
            /// </summary>
            public static ICSSoft.STORMNET.View D33_E
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("D33_E", typeof(IIS.CDLIB.D33));
                }
            }
            
            /// <summary>
            /// "FULLD33_E" view.
            /// </summary>
            public static ICSSoft.STORMNET.View FULLD33_E
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("FULLD33_E", typeof(IIS.CDLIB.D33));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of D33.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfD33 CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfD33 CustomAttributes)
    public class DetailArrayOfD33 : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.CDLIB.DetailArrayOfD33 members)

        // *** End programmer edit section *** (IIS.CDLIB.DetailArrayOfD33 members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type D33 by index.
        /// </summary>
        /// <summary>
        /// Adds object with type D33.
        /// </summary>
        public DetailArrayOfD33(IIS.CDLIB.D3 fD3) : 
                base(typeof(D33), ((ICSSoft.STORMNET.DataObject)(fD3)))
        {
        }
        
        public IIS.CDLIB.D33 this[int index]
        {
            get
            {
                return ((IIS.CDLIB.D33)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.CDLIB.D33 dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
