//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6Sample
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CDLIBEntities : DbContext
    {
        public CDLIBEntities()
            : base("name=CDLIBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BlueRay> BlueRay { get; set; }
        public virtual DbSet<CD> CD { get; set; }
        public virtual DbSet<CDDA> CDDA { get; set; }
        public virtual DbSet<CDDD> CDDD { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<D0> D0 { get; set; }
        public virtual DbSet<D1> D1 { get; set; }
        public virtual DbSet<D11> D11 { get; set; }
        public virtual DbSet<D111> D111 { get; set; }
        public virtual DbSet<D112> D112 { get; set; }
        public virtual DbSet<D113> D113 { get; set; }
        public virtual DbSet<D12> D12 { get; set; }
        public virtual DbSet<D121> D121 { get; set; }
        public virtual DbSet<D122> D122 { get; set; }
        public virtual DbSet<D123> D123 { get; set; }
        public virtual DbSet<D13> D13 { get; set; }
        public virtual DbSet<D131> D131 { get; set; }
        public virtual DbSet<D132> D132 { get; set; }
        public virtual DbSet<D133> D133 { get; set; }
        public virtual DbSet<D2> D2 { get; set; }
        public virtual DbSet<D21> D21 { get; set; }
        public virtual DbSet<D211> D211 { get; set; }
        public virtual DbSet<D212> D212 { get; set; }
        public virtual DbSet<D213> D213 { get; set; }
        public virtual DbSet<D22> D22 { get; set; }
        public virtual DbSet<D221> D221 { get; set; }
        public virtual DbSet<D222> D222 { get; set; }
        public virtual DbSet<D223> D223 { get; set; }
        public virtual DbSet<D23> D23 { get; set; }
        public virtual DbSet<D231> D231 { get; set; }
        public virtual DbSet<D232> D232 { get; set; }
        public virtual DbSet<D233> D233 { get; set; }
        public virtual DbSet<D3> D3 { get; set; }
        public virtual DbSet<D31> D31 { get; set; }
        public virtual DbSet<D311> D311 { get; set; }
        public virtual DbSet<D312> D312 { get; set; }
        public virtual DbSet<D313> D313 { get; set; }
        public virtual DbSet<D32> D32 { get; set; }
        public virtual DbSet<D321> D321 { get; set; }
        public virtual DbSet<D322> D322 { get; set; }
        public virtual DbSet<D323> D323 { get; set; }
        public virtual DbSet<D33> D33 { get; set; }
        public virtual DbSet<D331> D331 { get; set; }
        public virtual DbSet<D332> D332 { get; set; }
        public virtual DbSet<D333> D333 { get; set; }
        public virtual DbSet<DVD> DVD { get; set; }
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<Publisher> Publisher { get; set; }
        public virtual DbSet<Track> Track { get; set; }
    }
}
