//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6Sample
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.Publisher = new HashSet<Publisher>();
        }
    
        public System.Guid primaryKey { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Publisher> Publisher { get; set; }
    }
}
