//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6Sample
{
    using System;
    using System.Collections.Generic;
    
    public partial class D0
    {
        public D0()
        {
            this.D1 = new HashSet<D1>();
            this.D2 = new HashSet<D2>();
            this.D3 = new HashSet<D3>();
        }
    
        public System.Guid primaryKey { get; set; }
        public string Name { get; set; }
        public string S1 { get; set; }
        public string S2 { get; set; }
        public string S3 { get; set; }
        public string S4 { get; set; }
        public string S5 { get; set; }
    
        public virtual ICollection<D1> D1 { get; set; }
        public virtual ICollection<D2> D2 { get; set; }
        public virtual ICollection<D3> D3 { get; set; }
    }
}
