
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EF6Sample
{

using System;
    using System.Collections.Generic;
    
public partial class D1
{

    public D1()
    {

        this.D11 = new HashSet<D11>();

        this.D12 = new HashSet<D12>();

        this.D13 = new HashSet<D13>();

    }


    public System.Guid primaryKey { get; set; }

    public string Name { get; set; }

    public System.Guid D0 { get; set; }

    public string S1 { get; set; }

    public string S2 { get; set; }

    public string S3 { get; set; }

    public string S4 { get; set; }

    public string S5 { get; set; }



    public virtual D0 D01 { get; set; }

    public virtual ICollection<D11> D11 { get; set; }

    public virtual ICollection<D12> D12 { get; set; }

    public virtual ICollection<D13> D13 { get; set; }

}

}
