//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6Sample
{
    using System;
    using System.Collections.Generic;
    
    public partial class D12
    {
        public D12()
        {
            this.D121 = new HashSet<D121>();
            this.D122 = new HashSet<D122>();
            this.D123 = new HashSet<D123>();
        }
    
        public System.Guid primaryKey { get; set; }
        public string Name { get; set; }
        public System.Guid D1 { get; set; }
        public string S1 { get; set; }
        public string S2 { get; set; }
        public string S3 { get; set; }
        public string S4 { get; set; }
        public string S5 { get; set; }
    
        public virtual D1 D11 { get; set; }
        public virtual ICollection<D121> D121 { get; set; }
        public virtual ICollection<D122> D122 { get; set; }
        public virtual ICollection<D123> D123 { get; set; }
    }
}
