//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6Sample
{
    using System;
    using System.Collections.Generic;
    
    public partial class D21
    {
        public D21()
        {
            this.D211 = new HashSet<D211>();
            this.D212 = new HashSet<D212>();
            this.D213 = new HashSet<D213>();
        }
    
        public System.Guid primaryKey { get; set; }
        public string Name { get; set; }
        public System.Guid D2 { get; set; }
        public string S1 { get; set; }
        public string S2 { get; set; }
        public string S3 { get; set; }
        public string S4 { get; set; }
        public string S5 { get; set; }
    
        public virtual D2 D22 { get; set; }
        public virtual ICollection<D211> D211 { get; set; }
        public virtual ICollection<D212> D212 { get; set; }
        public virtual ICollection<D213> D213 { get; set; }
    }
}
