
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EF6Sample
{

using System;
    using System.Collections.Generic;
    
public partial class D22
{

    public D22()
    {

        this.D221 = new HashSet<D221>();

        this.D222 = new HashSet<D222>();

        this.D223 = new HashSet<D223>();

    }


    public System.Guid primaryKey { get; set; }

    public string Name { get; set; }

    public System.Guid D2 { get; set; }

    public string S1 { get; set; }

    public string S2 { get; set; }

    public string S3 { get; set; }

    public string S4 { get; set; }

    public string S5 { get; set; }



    public virtual D2 D21 { get; set; }

    public virtual ICollection<D221> D221 { get; set; }

    public virtual ICollection<D222> D222 { get; set; }

    public virtual ICollection<D223> D223 { get; set; }

}

}
