
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EF6Sample
{

using System;
    using System.Collections.Generic;
    
public partial class D23
{

    public D23()
    {

        this.D231 = new HashSet<D231>();

        this.D232 = new HashSet<D232>();

        this.D233 = new HashSet<D233>();

    }


    public System.Guid primaryKey { get; set; }

    public string Name { get; set; }

    public System.Guid D2 { get; set; }

    public string S1 { get; set; }

    public string S2 { get; set; }

    public string S3 { get; set; }

    public string S4 { get; set; }

    public string S5 { get; set; }



    public virtual D2 D21 { get; set; }

    public virtual ICollection<D231> D231 { get; set; }

    public virtual ICollection<D232> D232 { get; set; }

    public virtual ICollection<D233> D233 { get; set; }

}

}
