
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EF6Sample
{

using System;
    using System.Collections.Generic;
    
public partial class D31
{

    public D31()
    {

        this.D311 = new HashSet<D311>();

        this.D312 = new HashSet<D312>();

        this.D313 = new HashSet<D313>();

    }


    public System.Guid primaryKey { get; set; }

    public string Name { get; set; }

    public System.Guid D3 { get; set; }

    public string S1 { get; set; }

    public string S2 { get; set; }

    public string S3 { get; set; }

    public string S4 { get; set; }

    public string S5 { get; set; }



    public virtual D3 D32 { get; set; }

    public virtual ICollection<D311> D311 { get; set; }

    public virtual ICollection<D312> D312 { get; set; }

    public virtual ICollection<D313> D313 { get; set; }

}

}
