//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6Sample
{
    using System;
    using System.Collections.Generic;
    
    public partial class D32
    {
        public D32()
        {
            this.D321 = new HashSet<D321>();
            this.D322 = new HashSet<D322>();
            this.D323 = new HashSet<D323>();
        }
    
        public System.Guid primaryKey { get; set; }
        public string Name { get; set; }
        public System.Guid D3 { get; set; }
        public string S1 { get; set; }
        public string S2 { get; set; }
        public string S3 { get; set; }
        public string S4 { get; set; }
        public string S5 { get; set; }
    
        public virtual D3 D31 { get; set; }
        public virtual ICollection<D321> D321 { get; set; }
        public virtual ICollection<D322> D322 { get; set; }
        public virtual ICollection<D323> D323 { get; set; }
    }
}
