//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6Sample
{
    using System;
    using System.Collections.Generic;
    
    public partial class D33
    {
        public D33()
        {
            this.D331 = new HashSet<D331>();
            this.D332 = new HashSet<D332>();
            this.D333 = new HashSet<D333>();
        }
    
        public System.Guid primaryKey { get; set; }
        public string Name { get; set; }
        public System.Guid D3 { get; set; }
        public string S1 { get; set; }
        public string S2 { get; set; }
        public string S3 { get; set; }
        public string S4 { get; set; }
        public string S5 { get; set; }
    
        public virtual D3 D31 { get; set; }
        public virtual ICollection<D331> D331 { get; set; }
        public virtual ICollection<D332> D332 { get; set; }
        public virtual ICollection<D333> D333 { get; set; }
    }
}
