
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EF6Sample
{

using System;
    using System.Collections.Generic;
    
public partial class Internal
{

    public System.Guid primaryKey { get; set; }

    public string S0 { get; set; }

    public string S1 { get; set; }

    public string S2 { get; set; }

    public string S3 { get; set; }

    public string S4 { get; set; }

    public string S5 { get; set; }

    public string S6 { get; set; }

    public string S7 { get; set; }

    public string S8 { get; set; }

    public string S9 { get; set; }

    public System.Guid Master04 { get; set; }

    public System.Guid Master07 { get; set; }

    public System.Guid Master02 { get; set; }

    public System.Guid Master09 { get; set; }

    public System.Guid Master10 { get; set; }

    public System.Guid Master06 { get; set; }

    public Nullable<System.Guid> MasterSpecial_m0 { get; set; }

    public Nullable<System.Guid> MasterSpecial_m1 { get; set; }

    public Nullable<System.Guid> MasterSpecial_m2 { get; set; }

    public Nullable<System.Guid> MasterSpecial_m3 { get; set; }

    public System.Guid Master12 { get; set; }

    public System.Guid Master08 { get; set; }

    public System.Guid Master05 { get; set; }

    public System.Guid Master11 { get; set; }

    public System.Guid Master01 { get; set; }

    public System.Guid Master03 { get; set; }



    public virtual Master0 Master0 { get; set; }

    public virtual Master01 Master011 { get; set; }

    public virtual Master02 Master021 { get; set; }

    public virtual Master03 Master031 { get; set; }

    public virtual Master04 Master041 { get; set; }

    public virtual Master05 Master051 { get; set; }

    public virtual Master06 Master061 { get; set; }

    public virtual Master07 Master071 { get; set; }

    public virtual Master08 Master081 { get; set; }

    public virtual Master09 Master091 { get; set; }

    public virtual Master10 Master101 { get; set; }

    public virtual Master11 Master111 { get; set; }

    public virtual Master12 Master121 { get; set; }

    public virtual MasterDerived01 MasterDerived01 { get; set; }

    public virtual MasterDerived02 MasterDerived02 { get; set; }

    public virtual MasterDerived03 MasterDerived03 { get; set; }

}

}
