//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CDLIB
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Internal.
    /// </summary>
    // *** Start programmer edit section *** (Internal CustomAttributes)

    // *** End programmer edit section *** (Internal CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("FULLInternal_E", new string[] {
            "*",
            "Master01.*",
            "Master02.*",
            "Master03.*",
            "Master04.*",
            "Master05.*",
            "Master06.*",
            "Master07.*",
            "Master08.*",
            "Master09.*",
            "Master10.*",
            "Master11.*",
            "Master12.*",
            "MasterSpecial.*"}, Hidden=new string[] {
            "*"})]
    [View("Internal_E", new string[] {
            "S0",
            "Master01.S0",
            "Master02.S0",
            "Master03.S0",
            "Master04.S0",
            "Master05.S0",
            "Master06.S0",
            "Master07.S0",
            "Master08.S0",
            "Master09.S0",
            "Master10.S0",
            "Master11.S0",
            "Master12.S0",
            "MasterSpecial.S0"})]
    public class Internal : ICSSoft.STORMNET.DataObject
    {
        
        private string fS0;
        
        private string fS1;
        
        private string fS2;
        
        private string fS3;
        
        private string fS4;
        
        private string fS5;
        
        private string fS6;
        
        private string fS7;
        
        private string fS8;
        
        private string fS9;
        
        private IIS.CDLIB.Master04 fMaster04;
        
        private IIS.CDLIB.Master07 fMaster07;
        
        private IIS.CDLIB.Master02 fMaster02;
        
        private IIS.CDLIB.Master09 fMaster09;
        
        private IIS.CDLIB.Master10 fMaster10;
        
        private IIS.CDLIB.Master06 fMaster06;
        
        private IIS.CDLIB.Master0 fMasterSpecial;
        
        private IIS.CDLIB.Master12 fMaster12;
        
        private IIS.CDLIB.Master08 fMaster08;
        
        private IIS.CDLIB.Master05 fMaster05;
        
        private IIS.CDLIB.Master11 fMaster11;
        
        private IIS.CDLIB.Master01 fMaster01;
        
        private IIS.CDLIB.Master03 fMaster03;
        
        // *** Start programmer edit section *** (Internal CustomMembers)

        // *** End programmer edit section *** (Internal CustomMembers)

        
        /// <summary>
        /// S0.
        /// </summary>
        // *** Start programmer edit section *** (Internal.S0 CustomAttributes)

        // *** End programmer edit section *** (Internal.S0 CustomAttributes)
        [StrLen(255)]
        public virtual string S0
        {
            get
            {
                // *** Start programmer edit section *** (Internal.S0 Get start)

                // *** End programmer edit section *** (Internal.S0 Get start)
                string result = this.fS0;
                // *** Start programmer edit section *** (Internal.S0 Get end)

                // *** End programmer edit section *** (Internal.S0 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Internal.S0 Set start)

                // *** End programmer edit section *** (Internal.S0 Set start)
                this.fS0 = value;
                // *** Start programmer edit section *** (Internal.S0 Set end)

                // *** End programmer edit section *** (Internal.S0 Set end)
            }
        }
        
        /// <summary>
        /// S1.
        /// </summary>
        // *** Start programmer edit section *** (Internal.S1 CustomAttributes)

        // *** End programmer edit section *** (Internal.S1 CustomAttributes)
        [StrLen(255)]
        public virtual string S1
        {
            get
            {
                // *** Start programmer edit section *** (Internal.S1 Get start)

                // *** End programmer edit section *** (Internal.S1 Get start)
                string result = this.fS1;
                // *** Start programmer edit section *** (Internal.S1 Get end)

                // *** End programmer edit section *** (Internal.S1 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Internal.S1 Set start)

                // *** End programmer edit section *** (Internal.S1 Set start)
                this.fS1 = value;
                // *** Start programmer edit section *** (Internal.S1 Set end)

                // *** End programmer edit section *** (Internal.S1 Set end)
            }
        }
        
        /// <summary>
        /// S2.
        /// </summary>
        // *** Start programmer edit section *** (Internal.S2 CustomAttributes)

        // *** End programmer edit section *** (Internal.S2 CustomAttributes)
        [StrLen(255)]
        public virtual string S2
        {
            get
            {
                // *** Start programmer edit section *** (Internal.S2 Get start)

                // *** End programmer edit section *** (Internal.S2 Get start)
                string result = this.fS2;
                // *** Start programmer edit section *** (Internal.S2 Get end)

                // *** End programmer edit section *** (Internal.S2 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Internal.S2 Set start)

                // *** End programmer edit section *** (Internal.S2 Set start)
                this.fS2 = value;
                // *** Start programmer edit section *** (Internal.S2 Set end)

                // *** End programmer edit section *** (Internal.S2 Set end)
            }
        }
        
        /// <summary>
        /// S3.
        /// </summary>
        // *** Start programmer edit section *** (Internal.S3 CustomAttributes)

        // *** End programmer edit section *** (Internal.S3 CustomAttributes)
        [StrLen(255)]
        public virtual string S3
        {
            get
            {
                // *** Start programmer edit section *** (Internal.S3 Get start)

                // *** End programmer edit section *** (Internal.S3 Get start)
                string result = this.fS3;
                // *** Start programmer edit section *** (Internal.S3 Get end)

                // *** End programmer edit section *** (Internal.S3 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Internal.S3 Set start)

                // *** End programmer edit section *** (Internal.S3 Set start)
                this.fS3 = value;
                // *** Start programmer edit section *** (Internal.S3 Set end)

                // *** End programmer edit section *** (Internal.S3 Set end)
            }
        }
        
        /// <summary>
        /// S4.
        /// </summary>
        // *** Start programmer edit section *** (Internal.S4 CustomAttributes)

        // *** End programmer edit section *** (Internal.S4 CustomAttributes)
        [StrLen(255)]
        public virtual string S4
        {
            get
            {
                // *** Start programmer edit section *** (Internal.S4 Get start)

                // *** End programmer edit section *** (Internal.S4 Get start)
                string result = this.fS4;
                // *** Start programmer edit section *** (Internal.S4 Get end)

                // *** End programmer edit section *** (Internal.S4 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Internal.S4 Set start)

                // *** End programmer edit section *** (Internal.S4 Set start)
                this.fS4 = value;
                // *** Start programmer edit section *** (Internal.S4 Set end)

                // *** End programmer edit section *** (Internal.S4 Set end)
            }
        }
        
        /// <summary>
        /// S5.
        /// </summary>
        // *** Start programmer edit section *** (Internal.S5 CustomAttributes)

        // *** End programmer edit section *** (Internal.S5 CustomAttributes)
        [StrLen(255)]
        public virtual string S5
        {
            get
            {
                // *** Start programmer edit section *** (Internal.S5 Get start)

                // *** End programmer edit section *** (Internal.S5 Get start)
                string result = this.fS5;
                // *** Start programmer edit section *** (Internal.S5 Get end)

                // *** End programmer edit section *** (Internal.S5 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Internal.S5 Set start)

                // *** End programmer edit section *** (Internal.S5 Set start)
                this.fS5 = value;
                // *** Start programmer edit section *** (Internal.S5 Set end)

                // *** End programmer edit section *** (Internal.S5 Set end)
            }
        }
        
        /// <summary>
        /// S6.
        /// </summary>
        // *** Start programmer edit section *** (Internal.S6 CustomAttributes)

        // *** End programmer edit section *** (Internal.S6 CustomAttributes)
        [StrLen(255)]
        public virtual string S6
        {
            get
            {
                // *** Start programmer edit section *** (Internal.S6 Get start)

                // *** End programmer edit section *** (Internal.S6 Get start)
                string result = this.fS6;
                // *** Start programmer edit section *** (Internal.S6 Get end)

                // *** End programmer edit section *** (Internal.S6 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Internal.S6 Set start)

                // *** End programmer edit section *** (Internal.S6 Set start)
                this.fS6 = value;
                // *** Start programmer edit section *** (Internal.S6 Set end)

                // *** End programmer edit section *** (Internal.S6 Set end)
            }
        }
        
        /// <summary>
        /// S7.
        /// </summary>
        // *** Start programmer edit section *** (Internal.S7 CustomAttributes)

        // *** End programmer edit section *** (Internal.S7 CustomAttributes)
        [StrLen(255)]
        public virtual string S7
        {
            get
            {
                // *** Start programmer edit section *** (Internal.S7 Get start)

                // *** End programmer edit section *** (Internal.S7 Get start)
                string result = this.fS7;
                // *** Start programmer edit section *** (Internal.S7 Get end)

                // *** End programmer edit section *** (Internal.S7 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Internal.S7 Set start)

                // *** End programmer edit section *** (Internal.S7 Set start)
                this.fS7 = value;
                // *** Start programmer edit section *** (Internal.S7 Set end)

                // *** End programmer edit section *** (Internal.S7 Set end)
            }
        }
        
        /// <summary>
        /// S8.
        /// </summary>
        // *** Start programmer edit section *** (Internal.S8 CustomAttributes)

        // *** End programmer edit section *** (Internal.S8 CustomAttributes)
        [StrLen(255)]
        public virtual string S8
        {
            get
            {
                // *** Start programmer edit section *** (Internal.S8 Get start)

                // *** End programmer edit section *** (Internal.S8 Get start)
                string result = this.fS8;
                // *** Start programmer edit section *** (Internal.S8 Get end)

                // *** End programmer edit section *** (Internal.S8 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Internal.S8 Set start)

                // *** End programmer edit section *** (Internal.S8 Set start)
                this.fS8 = value;
                // *** Start programmer edit section *** (Internal.S8 Set end)

                // *** End programmer edit section *** (Internal.S8 Set end)
            }
        }
        
        /// <summary>
        /// S9.
        /// </summary>
        // *** Start programmer edit section *** (Internal.S9 CustomAttributes)

        // *** End programmer edit section *** (Internal.S9 CustomAttributes)
        [StrLen(255)]
        public virtual string S9
        {
            get
            {
                // *** Start programmer edit section *** (Internal.S9 Get start)

                // *** End programmer edit section *** (Internal.S9 Get start)
                string result = this.fS9;
                // *** Start programmer edit section *** (Internal.S9 Get end)

                // *** End programmer edit section *** (Internal.S9 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Internal.S9 Set start)

                // *** End programmer edit section *** (Internal.S9 Set start)
                this.fS9 = value;
                // *** Start programmer edit section *** (Internal.S9 Set end)

                // *** End programmer edit section *** (Internal.S9 Set end)
            }
        }
        
        /// <summary>
        /// Internal.
        /// </summary>
        // *** Start programmer edit section *** (Internal.Master04 CustomAttributes)

        // *** End programmer edit section *** (Internal.Master04 CustomAttributes)
        [PropertyStorage(new string[] {
                "Master04"})]
        [NotNull()]
        public virtual IIS.CDLIB.Master04 Master04
        {
            get
            {
                // *** Start programmer edit section *** (Internal.Master04 Get start)

                // *** End programmer edit section *** (Internal.Master04 Get start)
                IIS.CDLIB.Master04 result = this.fMaster04;
                // *** Start programmer edit section *** (Internal.Master04 Get end)

                // *** End programmer edit section *** (Internal.Master04 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Internal.Master04 Set start)

                // *** End programmer edit section *** (Internal.Master04 Set start)
                this.fMaster04 = value;
                // *** Start programmer edit section *** (Internal.Master04 Set end)

                // *** End programmer edit section *** (Internal.Master04 Set end)
            }
        }
        
        /// <summary>
        /// Internal.
        /// </summary>
        // *** Start programmer edit section *** (Internal.Master07 CustomAttributes)

        // *** End programmer edit section *** (Internal.Master07 CustomAttributes)
        [PropertyStorage(new string[] {
                "Master07"})]
        [NotNull()]
        public virtual IIS.CDLIB.Master07 Master07
        {
            get
            {
                // *** Start programmer edit section *** (Internal.Master07 Get start)

                // *** End programmer edit section *** (Internal.Master07 Get start)
                IIS.CDLIB.Master07 result = this.fMaster07;
                // *** Start programmer edit section *** (Internal.Master07 Get end)

                // *** End programmer edit section *** (Internal.Master07 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Internal.Master07 Set start)

                // *** End programmer edit section *** (Internal.Master07 Set start)
                this.fMaster07 = value;
                // *** Start programmer edit section *** (Internal.Master07 Set end)

                // *** End programmer edit section *** (Internal.Master07 Set end)
            }
        }
        
        /// <summary>
        /// Internal.
        /// </summary>
        // *** Start programmer edit section *** (Internal.Master02 CustomAttributes)

        // *** End programmer edit section *** (Internal.Master02 CustomAttributes)
        [PropertyStorage(new string[] {
                "Master02"})]
        [NotNull()]
        public virtual IIS.CDLIB.Master02 Master02
        {
            get
            {
                // *** Start programmer edit section *** (Internal.Master02 Get start)

                // *** End programmer edit section *** (Internal.Master02 Get start)
                IIS.CDLIB.Master02 result = this.fMaster02;
                // *** Start programmer edit section *** (Internal.Master02 Get end)

                // *** End programmer edit section *** (Internal.Master02 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Internal.Master02 Set start)

                // *** End programmer edit section *** (Internal.Master02 Set start)
                this.fMaster02 = value;
                // *** Start programmer edit section *** (Internal.Master02 Set end)

                // *** End programmer edit section *** (Internal.Master02 Set end)
            }
        }
        
        /// <summary>
        /// Internal.
        /// </summary>
        // *** Start programmer edit section *** (Internal.Master09 CustomAttributes)

        // *** End programmer edit section *** (Internal.Master09 CustomAttributes)
        [PropertyStorage(new string[] {
                "Master09"})]
        [NotNull()]
        public virtual IIS.CDLIB.Master09 Master09
        {
            get
            {
                // *** Start programmer edit section *** (Internal.Master09 Get start)

                // *** End programmer edit section *** (Internal.Master09 Get start)
                IIS.CDLIB.Master09 result = this.fMaster09;
                // *** Start programmer edit section *** (Internal.Master09 Get end)

                // *** End programmer edit section *** (Internal.Master09 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Internal.Master09 Set start)

                // *** End programmer edit section *** (Internal.Master09 Set start)
                this.fMaster09 = value;
                // *** Start programmer edit section *** (Internal.Master09 Set end)

                // *** End programmer edit section *** (Internal.Master09 Set end)
            }
        }
        
        /// <summary>
        /// Internal.
        /// </summary>
        // *** Start programmer edit section *** (Internal.Master10 CustomAttributes)

        // *** End programmer edit section *** (Internal.Master10 CustomAttributes)
        [PropertyStorage(new string[] {
                "Master10"})]
        [NotNull()]
        public virtual IIS.CDLIB.Master10 Master10
        {
            get
            {
                // *** Start programmer edit section *** (Internal.Master10 Get start)

                // *** End programmer edit section *** (Internal.Master10 Get start)
                IIS.CDLIB.Master10 result = this.fMaster10;
                // *** Start programmer edit section *** (Internal.Master10 Get end)

                // *** End programmer edit section *** (Internal.Master10 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Internal.Master10 Set start)

                // *** End programmer edit section *** (Internal.Master10 Set start)
                this.fMaster10 = value;
                // *** Start programmer edit section *** (Internal.Master10 Set end)

                // *** End programmer edit section *** (Internal.Master10 Set end)
            }
        }
        
        /// <summary>
        /// Internal.
        /// </summary>
        // *** Start programmer edit section *** (Internal.Master06 CustomAttributes)

        // *** End programmer edit section *** (Internal.Master06 CustomAttributes)
        [PropertyStorage(new string[] {
                "Master06"})]
        [NotNull()]
        public virtual IIS.CDLIB.Master06 Master06
        {
            get
            {
                // *** Start programmer edit section *** (Internal.Master06 Get start)

                // *** End programmer edit section *** (Internal.Master06 Get start)
                IIS.CDLIB.Master06 result = this.fMaster06;
                // *** Start programmer edit section *** (Internal.Master06 Get end)

                // *** End programmer edit section *** (Internal.Master06 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Internal.Master06 Set start)

                // *** End programmer edit section *** (Internal.Master06 Set start)
                this.fMaster06 = value;
                // *** Start programmer edit section *** (Internal.Master06 Set end)

                // *** End programmer edit section *** (Internal.Master06 Set end)
            }
        }
        
        /// <summary>
        /// Internal.
        /// </summary>
        // *** Start programmer edit section *** (Internal.MasterSpecial CustomAttributes)

        // *** End programmer edit section *** (Internal.MasterSpecial CustomAttributes)
        [PropertyStorage("MasterSpecial")]
        [TypeUsage(new string[] {
                "IIS.CDLIB.Master0",
                "IIS.CDLIB.MasterDerived01",
                "IIS.CDLIB.MasterDerived02",
                "IIS.CDLIB.MasterDerived03"})]
        [NotNull()]
        public virtual IIS.CDLIB.Master0 MasterSpecial
        {
            get
            {
                // *** Start programmer edit section *** (Internal.MasterSpecial Get start)

                // *** End programmer edit section *** (Internal.MasterSpecial Get start)
                IIS.CDLIB.Master0 result = this.fMasterSpecial;
                // *** Start programmer edit section *** (Internal.MasterSpecial Get end)

                // *** End programmer edit section *** (Internal.MasterSpecial Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Internal.MasterSpecial Set start)

                // *** End programmer edit section *** (Internal.MasterSpecial Set start)
                this.fMasterSpecial = value;
                // *** Start programmer edit section *** (Internal.MasterSpecial Set end)

                // *** End programmer edit section *** (Internal.MasterSpecial Set end)
            }
        }
        
        /// <summary>
        /// Internal.
        /// </summary>
        // *** Start programmer edit section *** (Internal.Master12 CustomAttributes)

        // *** End programmer edit section *** (Internal.Master12 CustomAttributes)
        [PropertyStorage(new string[] {
                "Master12"})]
        [NotNull()]
        public virtual IIS.CDLIB.Master12 Master12
        {
            get
            {
                // *** Start programmer edit section *** (Internal.Master12 Get start)

                // *** End programmer edit section *** (Internal.Master12 Get start)
                IIS.CDLIB.Master12 result = this.fMaster12;
                // *** Start programmer edit section *** (Internal.Master12 Get end)

                // *** End programmer edit section *** (Internal.Master12 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Internal.Master12 Set start)

                // *** End programmer edit section *** (Internal.Master12 Set start)
                this.fMaster12 = value;
                // *** Start programmer edit section *** (Internal.Master12 Set end)

                // *** End programmer edit section *** (Internal.Master12 Set end)
            }
        }
        
        /// <summary>
        /// Internal.
        /// </summary>
        // *** Start programmer edit section *** (Internal.Master08 CustomAttributes)

        // *** End programmer edit section *** (Internal.Master08 CustomAttributes)
        [PropertyStorage(new string[] {
                "Master08"})]
        [NotNull()]
        public virtual IIS.CDLIB.Master08 Master08
        {
            get
            {
                // *** Start programmer edit section *** (Internal.Master08 Get start)

                // *** End programmer edit section *** (Internal.Master08 Get start)
                IIS.CDLIB.Master08 result = this.fMaster08;
                // *** Start programmer edit section *** (Internal.Master08 Get end)

                // *** End programmer edit section *** (Internal.Master08 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Internal.Master08 Set start)

                // *** End programmer edit section *** (Internal.Master08 Set start)
                this.fMaster08 = value;
                // *** Start programmer edit section *** (Internal.Master08 Set end)

                // *** End programmer edit section *** (Internal.Master08 Set end)
            }
        }
        
        /// <summary>
        /// Internal.
        /// </summary>
        // *** Start programmer edit section *** (Internal.Master05 CustomAttributes)

        // *** End programmer edit section *** (Internal.Master05 CustomAttributes)
        [PropertyStorage(new string[] {
                "Master05"})]
        [NotNull()]
        public virtual IIS.CDLIB.Master05 Master05
        {
            get
            {
                // *** Start programmer edit section *** (Internal.Master05 Get start)

                // *** End programmer edit section *** (Internal.Master05 Get start)
                IIS.CDLIB.Master05 result = this.fMaster05;
                // *** Start programmer edit section *** (Internal.Master05 Get end)

                // *** End programmer edit section *** (Internal.Master05 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Internal.Master05 Set start)

                // *** End programmer edit section *** (Internal.Master05 Set start)
                this.fMaster05 = value;
                // *** Start programmer edit section *** (Internal.Master05 Set end)

                // *** End programmer edit section *** (Internal.Master05 Set end)
            }
        }
        
        /// <summary>
        /// Internal.
        /// </summary>
        // *** Start programmer edit section *** (Internal.Master11 CustomAttributes)

        // *** End programmer edit section *** (Internal.Master11 CustomAttributes)
        [PropertyStorage(new string[] {
                "Master11"})]
        [NotNull()]
        public virtual IIS.CDLIB.Master11 Master11
        {
            get
            {
                // *** Start programmer edit section *** (Internal.Master11 Get start)

                // *** End programmer edit section *** (Internal.Master11 Get start)
                IIS.CDLIB.Master11 result = this.fMaster11;
                // *** Start programmer edit section *** (Internal.Master11 Get end)

                // *** End programmer edit section *** (Internal.Master11 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Internal.Master11 Set start)

                // *** End programmer edit section *** (Internal.Master11 Set start)
                this.fMaster11 = value;
                // *** Start programmer edit section *** (Internal.Master11 Set end)

                // *** End programmer edit section *** (Internal.Master11 Set end)
            }
        }
        
        /// <summary>
        /// Internal.
        /// </summary>
        // *** Start programmer edit section *** (Internal.Master01 CustomAttributes)

        // *** End programmer edit section *** (Internal.Master01 CustomAttributes)
        [PropertyStorage(new string[] {
                "Master01"})]
        [NotNull()]
        public virtual IIS.CDLIB.Master01 Master01
        {
            get
            {
                // *** Start programmer edit section *** (Internal.Master01 Get start)

                // *** End programmer edit section *** (Internal.Master01 Get start)
                IIS.CDLIB.Master01 result = this.fMaster01;
                // *** Start programmer edit section *** (Internal.Master01 Get end)

                // *** End programmer edit section *** (Internal.Master01 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Internal.Master01 Set start)

                // *** End programmer edit section *** (Internal.Master01 Set start)
                this.fMaster01 = value;
                // *** Start programmer edit section *** (Internal.Master01 Set end)

                // *** End programmer edit section *** (Internal.Master01 Set end)
            }
        }
        
        /// <summary>
        /// Internal.
        /// </summary>
        // *** Start programmer edit section *** (Internal.Master03 CustomAttributes)

        // *** End programmer edit section *** (Internal.Master03 CustomAttributes)
        [PropertyStorage(new string[] {
                "Master03"})]
        [NotNull()]
        public virtual IIS.CDLIB.Master03 Master03
        {
            get
            {
                // *** Start programmer edit section *** (Internal.Master03 Get start)

                // *** End programmer edit section *** (Internal.Master03 Get start)
                IIS.CDLIB.Master03 result = this.fMaster03;
                // *** Start programmer edit section *** (Internal.Master03 Get end)

                // *** End programmer edit section *** (Internal.Master03 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Internal.Master03 Set start)

                // *** End programmer edit section *** (Internal.Master03 Set start)
                this.fMaster03 = value;
                // *** Start programmer edit section *** (Internal.Master03 Set end)

                // *** End programmer edit section *** (Internal.Master03 Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "FULLInternal_E" view.
            /// </summary>
            public static ICSSoft.STORMNET.View FULLInternal_E
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("FULLInternal_E", typeof(IIS.CDLIB.Internal));
                }
            }
            
            /// <summary>
            /// "Internal_E" view.
            /// </summary>
            public static ICSSoft.STORMNET.View Internal_E
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("Internal_E", typeof(IIS.CDLIB.Internal));
                }
            }
        }
    }
}
