//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CDLIB
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// MasterBase.
    /// </summary>
    // *** Start programmer edit section *** (MasterBase CustomAttributes)

    // *** End programmer edit section *** (MasterBase CustomAttributes)
    [AutoAltered()]
    [ICSSoft.STORMNET.NotStored()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("FULLMasterBase_E", new string[] {
            "*"}, Hidden=new string[] {
            "*"})]
    public class MasterBase : ICSSoft.STORMNET.DataObject
    {
        
        private string fS0;
        
        private string fS1;
        
        private string fS2;
        
        private string fS3;
        
        private string fS4;
        
        private string fS5;
        
        private string fS6;
        
        private string fS7;
        
        private string fS8;
        
        private string fS9;
        
        // *** Start programmer edit section *** (MasterBase CustomMembers)

        // *** End programmer edit section *** (MasterBase CustomMembers)

        
        /// <summary>
        /// S0.
        /// </summary>
        // *** Start programmer edit section *** (MasterBase.S0 CustomAttributes)

        // *** End programmer edit section *** (MasterBase.S0 CustomAttributes)
        [StrLen(255)]
        public virtual string S0
        {
            get
            {
                // *** Start programmer edit section *** (MasterBase.S0 Get start)

                // *** End programmer edit section *** (MasterBase.S0 Get start)
                string result = this.fS0;
                // *** Start programmer edit section *** (MasterBase.S0 Get end)

                // *** End programmer edit section *** (MasterBase.S0 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MasterBase.S0 Set start)

                // *** End programmer edit section *** (MasterBase.S0 Set start)
                this.fS0 = value;
                // *** Start programmer edit section *** (MasterBase.S0 Set end)

                // *** End programmer edit section *** (MasterBase.S0 Set end)
            }
        }
        
        /// <summary>
        /// S1.
        /// </summary>
        // *** Start programmer edit section *** (MasterBase.S1 CustomAttributes)

        // *** End programmer edit section *** (MasterBase.S1 CustomAttributes)
        [StrLen(255)]
        public virtual string S1
        {
            get
            {
                // *** Start programmer edit section *** (MasterBase.S1 Get start)

                // *** End programmer edit section *** (MasterBase.S1 Get start)
                string result = this.fS1;
                // *** Start programmer edit section *** (MasterBase.S1 Get end)

                // *** End programmer edit section *** (MasterBase.S1 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MasterBase.S1 Set start)

                // *** End programmer edit section *** (MasterBase.S1 Set start)
                this.fS1 = value;
                // *** Start programmer edit section *** (MasterBase.S1 Set end)

                // *** End programmer edit section *** (MasterBase.S1 Set end)
            }
        }
        
        /// <summary>
        /// S2.
        /// </summary>
        // *** Start programmer edit section *** (MasterBase.S2 CustomAttributes)

        // *** End programmer edit section *** (MasterBase.S2 CustomAttributes)
        [StrLen(255)]
        public virtual string S2
        {
            get
            {
                // *** Start programmer edit section *** (MasterBase.S2 Get start)

                // *** End programmer edit section *** (MasterBase.S2 Get start)
                string result = this.fS2;
                // *** Start programmer edit section *** (MasterBase.S2 Get end)

                // *** End programmer edit section *** (MasterBase.S2 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MasterBase.S2 Set start)

                // *** End programmer edit section *** (MasterBase.S2 Set start)
                this.fS2 = value;
                // *** Start programmer edit section *** (MasterBase.S2 Set end)

                // *** End programmer edit section *** (MasterBase.S2 Set end)
            }
        }
        
        /// <summary>
        /// S3.
        /// </summary>
        // *** Start programmer edit section *** (MasterBase.S3 CustomAttributes)

        // *** End programmer edit section *** (MasterBase.S3 CustomAttributes)
        [StrLen(255)]
        public virtual string S3
        {
            get
            {
                // *** Start programmer edit section *** (MasterBase.S3 Get start)

                // *** End programmer edit section *** (MasterBase.S3 Get start)
                string result = this.fS3;
                // *** Start programmer edit section *** (MasterBase.S3 Get end)

                // *** End programmer edit section *** (MasterBase.S3 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MasterBase.S3 Set start)

                // *** End programmer edit section *** (MasterBase.S3 Set start)
                this.fS3 = value;
                // *** Start programmer edit section *** (MasterBase.S3 Set end)

                // *** End programmer edit section *** (MasterBase.S3 Set end)
            }
        }
        
        /// <summary>
        /// S4.
        /// </summary>
        // *** Start programmer edit section *** (MasterBase.S4 CustomAttributes)

        // *** End programmer edit section *** (MasterBase.S4 CustomAttributes)
        [StrLen(255)]
        public virtual string S4
        {
            get
            {
                // *** Start programmer edit section *** (MasterBase.S4 Get start)

                // *** End programmer edit section *** (MasterBase.S4 Get start)
                string result = this.fS4;
                // *** Start programmer edit section *** (MasterBase.S4 Get end)

                // *** End programmer edit section *** (MasterBase.S4 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MasterBase.S4 Set start)

                // *** End programmer edit section *** (MasterBase.S4 Set start)
                this.fS4 = value;
                // *** Start programmer edit section *** (MasterBase.S4 Set end)

                // *** End programmer edit section *** (MasterBase.S4 Set end)
            }
        }
        
        /// <summary>
        /// S5.
        /// </summary>
        // *** Start programmer edit section *** (MasterBase.S5 CustomAttributes)

        // *** End programmer edit section *** (MasterBase.S5 CustomAttributes)
        [StrLen(255)]
        public virtual string S5
        {
            get
            {
                // *** Start programmer edit section *** (MasterBase.S5 Get start)

                // *** End programmer edit section *** (MasterBase.S5 Get start)
                string result = this.fS5;
                // *** Start programmer edit section *** (MasterBase.S5 Get end)

                // *** End programmer edit section *** (MasterBase.S5 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MasterBase.S5 Set start)

                // *** End programmer edit section *** (MasterBase.S5 Set start)
                this.fS5 = value;
                // *** Start programmer edit section *** (MasterBase.S5 Set end)

                // *** End programmer edit section *** (MasterBase.S5 Set end)
            }
        }
        
        /// <summary>
        /// S6.
        /// </summary>
        // *** Start programmer edit section *** (MasterBase.S6 CustomAttributes)

        // *** End programmer edit section *** (MasterBase.S6 CustomAttributes)
        [StrLen(255)]
        public virtual string S6
        {
            get
            {
                // *** Start programmer edit section *** (MasterBase.S6 Get start)

                // *** End programmer edit section *** (MasterBase.S6 Get start)
                string result = this.fS6;
                // *** Start programmer edit section *** (MasterBase.S6 Get end)

                // *** End programmer edit section *** (MasterBase.S6 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MasterBase.S6 Set start)

                // *** End programmer edit section *** (MasterBase.S6 Set start)
                this.fS6 = value;
                // *** Start programmer edit section *** (MasterBase.S6 Set end)

                // *** End programmer edit section *** (MasterBase.S6 Set end)
            }
        }
        
        /// <summary>
        /// S7.
        /// </summary>
        // *** Start programmer edit section *** (MasterBase.S7 CustomAttributes)

        // *** End programmer edit section *** (MasterBase.S7 CustomAttributes)
        [StrLen(255)]
        public virtual string S7
        {
            get
            {
                // *** Start programmer edit section *** (MasterBase.S7 Get start)

                // *** End programmer edit section *** (MasterBase.S7 Get start)
                string result = this.fS7;
                // *** Start programmer edit section *** (MasterBase.S7 Get end)

                // *** End programmer edit section *** (MasterBase.S7 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MasterBase.S7 Set start)

                // *** End programmer edit section *** (MasterBase.S7 Set start)
                this.fS7 = value;
                // *** Start programmer edit section *** (MasterBase.S7 Set end)

                // *** End programmer edit section *** (MasterBase.S7 Set end)
            }
        }
        
        /// <summary>
        /// S8.
        /// </summary>
        // *** Start programmer edit section *** (MasterBase.S8 CustomAttributes)

        // *** End programmer edit section *** (MasterBase.S8 CustomAttributes)
        [StrLen(255)]
        public virtual string S8
        {
            get
            {
                // *** Start programmer edit section *** (MasterBase.S8 Get start)

                // *** End programmer edit section *** (MasterBase.S8 Get start)
                string result = this.fS8;
                // *** Start programmer edit section *** (MasterBase.S8 Get end)

                // *** End programmer edit section *** (MasterBase.S8 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MasterBase.S8 Set start)

                // *** End programmer edit section *** (MasterBase.S8 Set start)
                this.fS8 = value;
                // *** Start programmer edit section *** (MasterBase.S8 Set end)

                // *** End programmer edit section *** (MasterBase.S8 Set end)
            }
        }
        
        /// <summary>
        /// S9.
        /// </summary>
        // *** Start programmer edit section *** (MasterBase.S9 CustomAttributes)

        // *** End programmer edit section *** (MasterBase.S9 CustomAttributes)
        [StrLen(255)]
        public virtual string S9
        {
            get
            {
                // *** Start programmer edit section *** (MasterBase.S9 Get start)

                // *** End programmer edit section *** (MasterBase.S9 Get start)
                string result = this.fS9;
                // *** Start programmer edit section *** (MasterBase.S9 Get end)

                // *** End programmer edit section *** (MasterBase.S9 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MasterBase.S9 Set start)

                // *** End programmer edit section *** (MasterBase.S9 Set start)
                this.fS9 = value;
                // *** Start programmer edit section *** (MasterBase.S9 Set end)

                // *** End programmer edit section *** (MasterBase.S9 Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "FULLMasterBase_E" view.
            /// </summary>
            public static ICSSoft.STORMNET.View FULLMasterBase_E
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("FULLMasterBase_E", typeof(IIS.CDLIB.MasterBase));
                }
            }
        }
    }
}
