//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CDLIB
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Master01.
    /// </summary>
    // *** Start programmer edit section *** (Master01 CustomAttributes)

    // *** End programmer edit section *** (Master01 CustomAttributes)
    [AutoAltered()]
    [ICSSoft.STORMNET.NotStored(false)]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class Master01 : IIS.CDLIB.MasterBase
    {
        
        // *** Start programmer edit section *** (Master01 CustomMembers)

        // *** End programmer edit section *** (Master01 CustomMembers)

    }
}
