//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CDLIB
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// BlueRay.
    /// </summary>
    // *** Start programmer edit section *** (BlueRay CustomAttributes)

    // *** End programmer edit section *** (BlueRay CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class BlueRay : IIS.CDLIB.CDDD
    {
        
        // *** Start programmer edit section *** (BlueRay CustomMembers)

        // *** End programmer edit section *** (BlueRay CustomMembers)

    }
}
