//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CDLIB
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// CD.
    /// </summary>
    // *** Start programmer edit section *** (CD CustomAttributes)

    // *** End programmer edit section *** (CD CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("CD_E", new string[] {
            "Name",
            "Publisher.Name",
            "Publisher.Country.Name"})]
    public class CD : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        private IIS.CDLIB.Publisher fPublisher;
        
        // *** Start programmer edit section *** (CD CustomMembers)

        // *** End programmer edit section *** (CD CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (CD.Name CustomAttributes)

        // *** End programmer edit section *** (CD.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (CD.Name Get start)

                // *** End programmer edit section *** (CD.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (CD.Name Get end)

                // *** End programmer edit section *** (CD.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (CD.Name Set start)

                // *** End programmer edit section *** (CD.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (CD.Name Set end)

                // *** End programmer edit section *** (CD.Name Set end)
            }
        }
        
        /// <summary>
        /// CD.
        /// </summary>
        // *** Start programmer edit section *** (CD.Publisher CustomAttributes)

        // *** End programmer edit section *** (CD.Publisher CustomAttributes)
        [PropertyStorage(new string[] {
                "Publisher"})]
        [NotNull()]
        public virtual IIS.CDLIB.Publisher Publisher
        {
            get
            {
                // *** Start programmer edit section *** (CD.Publisher Get start)

                // *** End programmer edit section *** (CD.Publisher Get start)
                IIS.CDLIB.Publisher result = this.fPublisher;
                // *** Start programmer edit section *** (CD.Publisher Get end)

                // *** End programmer edit section *** (CD.Publisher Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (CD.Publisher Set start)

                // *** End programmer edit section *** (CD.Publisher Set start)
                this.fPublisher = value;
                // *** Start programmer edit section *** (CD.Publisher Set end)

                // *** End programmer edit section *** (CD.Publisher Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "CD_E" view.
            /// </summary>
            public static ICSSoft.STORMNET.View CD_E
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("CD_E", typeof(IIS.CDLIB.CD));
                }
            }
        }
    }
}
