//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CDLIB
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// CDDA.
    /// </summary>
    // *** Start programmer edit section *** (CDDA CustomAttributes)

    // *** End programmer edit section *** (CDDA CustomAttributes)
    [BusinessServer("IIS.CDLIB.CDLibBS, CDLIB(BusinessServers)", ICSSoft.STORMNET.Business.DataServiceObjectEvents.OnAllEvents)]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("CDDA_E", new string[] {
            "Name",
            "TotalTracks",
            "Publisher.Name",
            "Publisher.Country.Name"})]
    [AssociatedDetailViewAttribute("CDDA_E", "Track", "Track_E", true, "", "", true, new string[] {
            ""})]
    public class CDDA : IIS.CDLIB.CD
    {
        
        private int fTotalTracks;
        
        private IIS.CDLIB.DetailArrayOfTrack fTrack;
        
        // *** Start programmer edit section *** (CDDA CustomMembers)

        // *** End programmer edit section *** (CDDA CustomMembers)

        
        /// <summary>
        /// TotalTracks.
        /// </summary>
        // *** Start programmer edit section *** (CDDA.TotalTracks CustomAttributes)

        // *** End programmer edit section *** (CDDA.TotalTracks CustomAttributes)
        public virtual int TotalTracks
        {
            get
            {
                // *** Start programmer edit section *** (CDDA.TotalTracks Get start)

                // *** End programmer edit section *** (CDDA.TotalTracks Get start)
                int result = this.fTotalTracks;
                // *** Start programmer edit section *** (CDDA.TotalTracks Get end)

                // *** End programmer edit section *** (CDDA.TotalTracks Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (CDDA.TotalTracks Set start)

                // *** End programmer edit section *** (CDDA.TotalTracks Set start)
                this.fTotalTracks = value;
                // *** Start programmer edit section *** (CDDA.TotalTracks Set end)

                // *** End programmer edit section *** (CDDA.TotalTracks Set end)
            }
        }
        
        /// <summary>
        /// CDDA.
        /// </summary>
        // *** Start programmer edit section *** (CDDA.Track CustomAttributes)

        // *** End programmer edit section *** (CDDA.Track CustomAttributes)
        public virtual IIS.CDLIB.DetailArrayOfTrack Track
        {
            get
            {
                // *** Start programmer edit section *** (CDDA.Track Get start)

                // *** End programmer edit section *** (CDDA.Track Get start)
                if ((this.fTrack == null))
                {
                    this.fTrack = new IIS.CDLIB.DetailArrayOfTrack(this);
                }
                IIS.CDLIB.DetailArrayOfTrack result = this.fTrack;
                // *** Start programmer edit section *** (CDDA.Track Get end)

                // *** End programmer edit section *** (CDDA.Track Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (CDDA.Track Set start)

                // *** End programmer edit section *** (CDDA.Track Set start)
                this.fTrack = value;
                // *** Start programmer edit section *** (CDDA.Track Set end)

                // *** End programmer edit section *** (CDDA.Track Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "CDDA_E" view.
            /// </summary>
            public static ICSSoft.STORMNET.View CDDA_E
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("CDDA_E", typeof(IIS.CDLIB.CDDA));
                }
            }
        }
    }
}
