//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CDLIB
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// CDDD.
    /// </summary>
    // *** Start programmer edit section *** (CDDD CustomAttributes)

    // *** End programmer edit section *** (CDDD CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class CDDD : IIS.CDLIB.CD
    {
        
        private int fCapacity;
        
        // *** Start programmer edit section *** (CDDD CustomMembers)

        // *** End programmer edit section *** (CDDD CustomMembers)

        
        /// <summary>
        /// Capacity.
        /// </summary>
        // *** Start programmer edit section *** (CDDD.Capacity CustomAttributes)

        // *** End programmer edit section *** (CDDD.Capacity CustomAttributes)
        public virtual int Capacity
        {
            get
            {
                // *** Start programmer edit section *** (CDDD.Capacity Get start)

                // *** End programmer edit section *** (CDDD.Capacity Get start)
                int result = this.fCapacity;
                // *** Start programmer edit section *** (CDDD.Capacity Get end)

                // *** End programmer edit section *** (CDDD.Capacity Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (CDDD.Capacity Set start)

                // *** End programmer edit section *** (CDDD.Capacity Set start)
                this.fCapacity = value;
                // *** Start programmer edit section *** (CDDD.Capacity Set end)

                // *** End programmer edit section *** (CDDD.Capacity Set end)
            }
        }
    }
}
