//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CDLIB
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// DVD.
    /// </summary>
    // *** Start programmer edit section *** (DVD CustomAttributes)

    // *** End programmer edit section *** (DVD CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class DVD : IIS.CDLIB.CDDD
    {
        
        private IIS.CDLIB.DVDVersion fVersion;
        
        // *** Start programmer edit section *** (DVD CustomMembers)

        // *** End programmer edit section *** (DVD CustomMembers)

        
        /// <summary>
        /// Version.
        /// </summary>
        // *** Start programmer edit section *** (DVD.Version CustomAttributes)

        // *** End programmer edit section *** (DVD.Version CustomAttributes)
        public virtual IIS.CDLIB.DVDVersion Version
        {
            get
            {
                // *** Start programmer edit section *** (DVD.Version Get start)

                // *** End programmer edit section *** (DVD.Version Get start)
                IIS.CDLIB.DVDVersion result = this.fVersion;
                // *** Start programmer edit section *** (DVD.Version Get end)

                // *** End programmer edit section *** (DVD.Version Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (DVD.Version Set start)

                // *** End programmer edit section *** (DVD.Version Set start)
                this.fVersion = value;
                // *** Start programmer edit section *** (DVD.Version Set end)

                // *** End programmer edit section *** (DVD.Version Set end)
            }
        }
    }
}
