//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CDLIB
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// DVDVersion.
    /// </summary>
    // *** Start programmer edit section *** (DVDVersion CustomAttributes)

    // *** End programmer edit section *** (DVDVersion CustomAttributes)
    public enum DVDVersion
    {
        
        // *** Start programmer edit section *** (DVDVersion.DVD5 CustomAttributes)

        // *** End programmer edit section *** (DVDVersion.DVD5 CustomAttributes)
        DVD5,
        
        // *** Start programmer edit section *** (DVDVersion.DVD9 CustomAttributes)

        // *** End programmer edit section *** (DVDVersion.DVD9 CustomAttributes)
        DVD9,
    }
}
