//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("CDLIB")]
[assembly: System.Reflection.AssemblyDescription("CDLIB")]
[assembly: System.Reflection.AssemblyConfiguration("")]
[assembly: System.Reflection.AssemblyCompany("IIS")]
[assembly: System.Reflection.AssemblyProduct("CDLIB")]
[assembly: System.Reflection.AssemblyCopyright("(c) 2004-2014. IIS ZAO. All rights reserved.")]
[assembly: System.Reflection.AssemblyTrademark("")]
[assembly: System.Reflection.AssemblyDelaySign(false)]
[assembly: System.Reflection.AssemblyKeyName("")]
[assembly: System.Reflection.AssemblyVersion("1.0.0.1")]
[assembly: System.Reflection.AssemblyKeyFile("")]

