//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CDLIB
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// CustomDBMasterClass.
    /// </summary>
    // *** Start programmer edit section *** (CustomDBMasterClass CustomAttributes)

    // *** End programmer edit section *** (CustomDBMasterClass CustomAttributes)
    [ClassStorage("CustomDBMaster")]
    [PrimaryKeyStorage("pkey")]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class CustomDBMasterClass : ICSSoft.STORMNET.DataObject
    {
        
        private string fCustomMasterAttribute;
        
        // *** Start programmer edit section *** (CustomDBMasterClass CustomMembers)

        // *** End programmer edit section *** (CustomDBMasterClass CustomMembers)

        
        /// <summary>
        /// CustomMasterAttribute.
        /// </summary>
        // *** Start programmer edit section *** (CustomDBMasterClass.CustomMasterAttribute CustomAttributes)

        // *** End programmer edit section *** (CustomDBMasterClass.CustomMasterAttribute CustomAttributes)
        [PropertyStorage("CustomAttribute")]
        [StrLen(255)]
        public virtual string CustomMasterAttribute
        {
            get
            {
                // *** Start programmer edit section *** (CustomDBMasterClass.CustomMasterAttribute Get start)

                // *** End programmer edit section *** (CustomDBMasterClass.CustomMasterAttribute Get start)
                string result = this.fCustomMasterAttribute;
                // *** Start programmer edit section *** (CustomDBMasterClass.CustomMasterAttribute Get end)

                // *** End programmer edit section *** (CustomDBMasterClass.CustomMasterAttribute Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (CustomDBMasterClass.CustomMasterAttribute Set start)

                // *** End programmer edit section *** (CustomDBMasterClass.CustomMasterAttribute Set start)
                this.fCustomMasterAttribute = value;
                // *** Start programmer edit section *** (CustomDBMasterClass.CustomMasterAttribute Set end)

                // *** End programmer edit section *** (CustomDBMasterClass.CustomMasterAttribute Set end)
            }
        }
    }
}
