//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CDLIB
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// CDLibBS.
    /// </summary>
    // *** Start programmer edit section *** (CDLibBS CustomAttributes)

    // *** End programmer edit section *** (CDLibBS CustomAttributes)
    [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class CDLibBS : ICSSoft.STORMNET.Business.BusinessServer
    {
        
        // *** Start programmer edit section *** (CDLibBS CustomMembers)

        // *** End programmer edit section *** (CDLibBS CustomMembers)

        
        // *** Start programmer edit section *** (OnUpdateCDDA CustomAttributes)

        // *** End programmer edit section *** (OnUpdateCDDA CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateCDDA(IIS.CDLIB.CDDA UpdatedObject)
        {
            // *** Start programmer edit section *** (OnUpdateCDDA)
            // There is a good place to add your custom code.
            // Don't make changes out of programmer edit section. They will be lost after overgeneration by Flexberry.

            // TotalTracks property needs to have same value as tracks counter. 
            UpdatedObject.TotalTracks = UpdatedObject.Track.Count;
            // Also, you can return additional dataobjects, - they will be updated with all objects in a single transaction
            return new ICSSoft.STORMNET.DataObject[0];
            // *** End programmer edit section *** (OnUpdateCDDA)
        }
    }
}
